
include(ExternalProject)
if(NOT SPDLOG_EXTERNAL_SOURCE)
	set(SPDLOG_EXTERNAL_SOURCE ${CMAKE_CURRENT_SOURCE_DIR}/external/spdlog-v1.x.zip)
endif()

set(SPDLOG_INSTALL_DIR ${CMAKE_INSTALL_PREFIX}/muq_external)

ExternalProject_Add(
	SPDLOG
                PREFIX ${CMAKE_CURRENT_BINARY_DIR}/external/spdlog
                URL ${SPDLOG_EXTERNAL_SOURCE}
                CMAKE_ARGS -DCMAKE_INSTALL_PREFIX=${SPDLOG_INSTALL_DIR} -DCMAKE_POSITION_INDEPENDENT_CODE=ON
#                BUILD_COMMAND ""
#                CONFIGURE_COMMAND ""
#                INSTALL_COMMAND ${CMAKE_COMMAND} -E make_directory ${SPDLOG_INSTALL_DIR}/include && cp -r ${CMAKE_CURRENT_BINARY_DIR}/external/spdlog/src/SPDLOG/include/spdlog ${EIGEN3_INSTALL_DIR}/include
)
#set(SUNDIALS_INCLUDE_DIRS ${SUNDIALS_INSTALL_DIR}/include )
#set(SUNDIALS_INCLUDE_DIR ${SUNDIALS_INCLUDE_DIRS})

#set(SUNDIALS_LIBRARY ${SUNDIALS_LIBRARIES})

set(SPDLOG_LIBRARIES ${PARCER_INSTALL_DIR}/lib/${CMAKE_STATIC_LIBRARY_PREFIX}spdlog${CMAKE_STATIC_LIBRARY_SUFFIX})
set(SPDLOG_LIBRARY ${SPDLOG_LIBRARIES})

set(SPDLOG_INCLUDE_DIRS ${SPDLOG_INSTALL_DIR}/include)
message(STATUS "Adding ${SPDLOG_INCLUDE_DIRS} for an SPDLOG include directory.")

set(MUQ_HAS_SPDLOG 1)