
include(ExternalProject)
if(NOT FLANN_EXTERNAL_SOURCE)
	set(FLANN_EXTERNAL_SOURCE http://www.cs.ubc.ca/research/flann/uploads/FLANN/flann-1.8.4-src.zip)
endif()

set(FLANN_INSTALL_DIR ${CMAKE_INSTALL_PREFIX}/muq_external/)

ExternalProject_Add(
FLANN
  PREFIX ${CMAKE_CURRENT_BINARY_DIR}/external/flann
  PATCH_COMMAND cp  ${CMAKE_SOURCE_DIR}/external/flann/CMakeLists.txt ${CMAKE_CURRENT_BINARY_DIR}/external/flann/src/FLANN/examples/CMakeLists.txt
  UPDATE_COMMAND cp ${CMAKE_SOURCE_DIR}/external/flann/nn_index.h ${CMAKE_CURRENT_BINARY_DIR}/external/flann/src/FLANN/src/cpp/flann/algorithms/nn_index.h
  URL ${FLANN_EXTERNAL_SOURCE}
  CMAKE_ARGS -DCMAKE_INSTALL_PREFIX=${FLANN_INSTALL_DIR} -DBUILD_CUDA_LIB=OFF -DBUILD_MATLAB_BINDINGS=OFF -DBUILD_PYTHON_BINDINGS=OFF -DBUILD_C_BINDINGS=OFF -DUSE_OPENMP=${MUQ_USE_OPENMP} -DUSE_MPI=OFF -DBUILD_EXAMPLE=OFF
  INSTALL_COMMAND make install
)


set_property( TARGET FLANN PROPERTY FOLDER "Externals")

set(FLANN_INCLUDE_DIRS ${FLANN_INSTALL_DIR}/include )
set(FLANN_LIBRARIES ${FLANN_INSTALL_DIR}/lib/${CMAKE_SHARED_LIBRARY_PREFIX}flann_cpp${CMAKE_SHARED_LIBRARY_SUFFIX})
set(FLANN_LIBRARIES_STATIC ${FLANN_INSTALL_DIR}/lib/${CMAKE_STATIC_LIBRARY_PREFIX}flann_cpp_s${CMAKE_STATIC_LIBRARY_SUFFIX})


