MUQ: /Users/andy/software/muq-private/external/include/stan/agrad/agrad.hpp File Reference
agrad.hpp File Reference
#include <cmath>
#include <cstddef>
#include <limits>
#include <stdexcept>
#include <vector>
#include <ostream>
#include <iostream>
#include <stan/memory/stack_alloc.hpp>
Functions
int std::isnan (const stan::agrad::var &a)
int std::isinf (const stan::agrad::var &a)
Function Documentation
isinf()
int std::isinf (const stan::agrad::var & a) inline
Checks if the given number is infinite.
Return true if the value of the a is positive or negative infinity.
Parameters
a Variable to test.
Returns
true if value is infinite.
Definition at line 2387 of file agrad.hpp.
References std::isinf().
Referenced by std::isinf().
isnan()
int std::isnan (const stan::agrad::var & a) inline
Checks if the given number is NaN.
Return true if the value of the specified variable is not a number.
Parameters
a Variable to test.
Returns
true if value is not a number.
Definition at line 2374 of file agrad.hpp.
References std::isnan().
Referenced by std::isnan().
Variable Documentation
ad_
double ad_ protected
Definition at line 648 of file agrad.hpp.
avi_
vari* avi_ protected
Definition at line 614 of file agrad.hpp.
bd_
double bd_ protected
Definition at line 637 of file agrad.hpp.
bvi_
vari* bvi_ protected
Definition at line 625 of file agrad.hpp.
cd_
double cd_ protected
Definition at line 676 of file agrad.hpp.
cvi_
vari* cvi_ protected
Definition at line 662 of file agrad.hpp.
da_
double da_ protected
Definition at line 759 of file agrad.hpp.
exp_val_
const double exp_val_
Definition at line 951 of file agrad.hpp.
size_
const size_t size_ protected
Definition at line 773 of file agrad.hpp.
vis_
vari** vis_ protected
Definition at line 774 of file agrad.hpp.