MUQ: muq::Utilities::H5Object Class Reference
muq::Utilities::H5Object Class Reference
#include <H5Object.h>
Detailed Description
Definition at line 53 of file H5Object.h.
Public Member Functions
H5Object ()
H5Object (std::shared_ptr< HDF5File > file_, std::string const &path_, bool isDataset_)
template<typename ScalarType , typename = typename std::enable_if<std::is_arithmetic<ScalarType>::value, ScalarType>::type>
H5Object & operator= (ScalarType val)
template<typename MatrixType , typename = typename std::enable_if< !std::is_arithmetic<MatrixType>::value, MatrixType>::type>
H5Object & operator= (MatrixType const &val)
template<typename ScalarType , int fixedRows, int fixedCols>
H5Object & operator= (Eigen::Matrix< ScalarType, fixedRows, fixedCols > const &val)
template<typename scalarType = double, int rows = Eigen::Dynamic, int cols = Eigen::Dynamic>
Eigen::Matrix< scalarType, rows, cols > eval ()
H5Object & CreateDataset (std::string const &grpName)
H5Object & CreateGroup (std::string const &grpName)
H5Object & operator[] (std::string const &targetPath)
BlockDataset block (unsigned startRow, unsigned startCol, unsigned numRows, unsigned numCols) const
BlockDataset topLeftCorner (unsigned numRows, unsigned numCols) const
BlockDataset bottomLeftCorner (unsigned numRows, unsigned numCols) const
BlockDataset topRightCorner (unsigned numRows, unsigned numCols) const
BlockDataset bottomRightCorner (unsigned numRows, unsigned numCols) const
BlockDataset topRows (unsigned numRows) const
BlockDataset bottomRows (unsigned numRows) const
BlockDataset leftCols (unsigned numCols) const
BlockDataset rightCols (unsigned numCols) const
BlockDataset col (unsigned col) const
BlockDataset row (unsigned row) const
BlockDataset segment (unsigned startInd, unsigned numInds) const
BlockDataset head (unsigned numInds) const
BlockDataset tail (unsigned numInds) const
unsigned rows () const
unsigned cols () const
unsigned size () const
double operator() (int i) const
double operator() (int i, int j) const
void Flush ()
void Print (std::string prefix="") const
Public Attributes
std::shared_ptr< HDF5File > file
AttributeList attrs
Friends
H5Object muq::Utilities::AddChildren (std::shared_ptr< HDF5File > file, std::string const &path)
Constructor & Destructor Documentation
H5Object() [1/2]
muq::Utilities::H5Object::H5Object () inline
Definition at line 59 of file H5Object.h.
Referenced by muq::Utilities::AddChildren(), CreateDataset(), and CreateGroup().
H5Object() [2/2]
muq::Utilities::H5Object::H5Object (std::shared_ptr< HDF5File > file_, std::string const & path_, bool isDataset_) inline
Definition at line 61 of file H5Object.h.
Member Function Documentation
block()
BlockDataset H5Object::block (unsigned startRow, unsigned startCol, unsigned numRows, unsigned numCols) const
Definition at line 108 of file H5Object.cpp.
References file, isDataset, and path.
Referenced by bottomLeftCorner(), bottomRightCorner(), bottomRows(), col(), eval(), head(), leftCols(), rightCols(), row(), segment(), tail(), topLeftCorner(), topRightCorner(), and topRows().
bottomLeftCorner()
BlockDataset H5Object::bottomLeftCorner (unsigned numRows, unsigned numCols) const
Definition at line 124 of file H5Object.cpp.
References block(), and rows().
Referenced by eval().
bottomRightCorner()
BlockDataset H5Object::bottomRightCorner (unsigned numRows, unsigned numCols) const
Definition at line 134 of file H5Object.cpp.
References block(), cols(), and rows().
Referenced by eval().
bottomRows()
BlockDataset H5Object::bottomRows (unsigned numRows) const
Definition at line 144 of file H5Object.cpp.
References block(), and cols().
Referenced by eval().
col()
BlockDataset H5Object::col (unsigned col) const
Definition at line 159 of file H5Object.cpp.
References block(), file, isDataset, and path.
Referenced by eval().
cols()
unsigned H5Object::cols () const
Definition at line 198 of file H5Object.cpp.
References file, and path.
Referenced by bottomRightCorner(), bottomRows(), eval(), rightCols(), topRightCorner(), and topRows().
CreateDataset()
H5Object & H5Object::CreateDataset (std::string const & grpName)
Definition at line 6 of file H5Object.cpp.
References children, file, H5Object(), path, and muq::Utilities::SplitString().
Referenced by eval(), and operator[]().
CreateGroup()
H5Object & H5Object::CreateGroup (std::string const & grpName)
Definition at line 36 of file H5Object.cpp.
References children, file, H5Object(), path, and muq::Utilities::SplitString().
Referenced by eval().
eval()
template<typename scalarType = double, int rows = Eigen::Dynamic, int cols = Eigen::Dynamic> Eigen::Matrix<scalarType,rows,cols> muq::Utilities::H5Object::eval () inline
Definition at line 118 of file H5Object.h.
References block(), bottomLeftCorner(), bottomRightCorner(), bottomRows(), col(), cols(), CreateDataset(), CreateGroup(), Flush(), head(), isDataset, leftCols(), operator()(), operator[](), path, Print(), rightCols(), row(), rows(), segment(), size(), FindPtreeParameters::startInd, tail(), topLeftCorner(), topRightCorner(), and topRows().
Referenced by operator=().
Flush()
void H5Object::Flush ()
Definition at line 237 of file H5Object.cpp.
References file.
Referenced by eval().
head()
BlockDataset H5Object::head (unsigned numInds) const
Definition at line 181 of file H5Object.cpp.
References block().
Referenced by eval().
leftCols()
BlockDataset H5Object::leftCols (unsigned numCols) const
Definition at line 149 of file H5Object.cpp.
References block(), and rows().
Referenced by eval().
operator()() [1/2]
double H5Object::operator() (int i) const
Definition at line 211 of file H5Object.cpp.
References file, isDataset, and path.
Referenced by eval().
operator()() [2/2]
double H5Object::operator() (int i, int j) const
Definition at line 223 of file H5Object.cpp.
References file, isDataset, and path.
operator=() [1/3]
template<typename ScalarType , typename = typename std::enable_if<std::is_arithmetic<ScalarType>::value, ScalarType>::type> H5Object& muq::Utilities::H5Object::operator= (ScalarType val) inline
Definition at line 71 of file H5Object.h.
References isDataset.
operator=() [2/3]
template<typename MatrixType , typename = typename std::enable_if< !std::is_arithmetic<MatrixType>::value, MatrixType>::type> H5Object& muq::Utilities::H5Object::operator= (MatrixType const & val) inline
Definition at line 90 of file H5Object.h.
References eval().
operator=() [3/3]
template<typename ScalarType , int fixedRows, int fixedCols> H5Object& muq::Utilities::H5Object::operator= (Eigen::Matrix< ScalarType, fixedRows, fixedCols > const & val) inline
Definition at line 96 of file H5Object.h.
References isDataset.
operator[]()
H5Object & H5Object::operator[] (std::string const & targetPath)
Definition at line 68 of file H5Object.cpp.
References children, CreateDataset(), isDataset, and muq::Utilities::SplitString().
Referenced by eval().
Print()
void H5Object::Print (std::string prefix = "") const
Definition at line 243 of file H5Object.cpp.
References FindPtreeParameters::child, children, and path.
Referenced by eval().
rightCols()
BlockDataset H5Object::rightCols (unsigned numCols) const
Definition at line 154 of file H5Object.cpp.
References block(), cols(), and rows().
Referenced by eval().
row()
BlockDataset H5Object::row (unsigned row) const
Definition at line 168 of file H5Object.cpp.
References block(), file, isDataset, and path.
Referenced by eval().
rows()
unsigned H5Object::rows () const
Definition at line 192 of file H5Object.cpp.
References file, and path.
Referenced by bottomLeftCorner(), bottomRightCorner(), eval(), leftCols(), rightCols(), and tail().
segment()
BlockDataset H5Object::segment (unsigned startInd, unsigned numInds) const
Definition at line 176 of file H5Object.cpp.
References block().
Referenced by eval().
size()
unsigned H5Object::size () const
Definition at line 205 of file H5Object.cpp.
References file, and path.
Referenced by eval().
tail()
BlockDataset H5Object::tail (unsigned numInds) const
Definition at line 186 of file H5Object.cpp.
References block(), and rows().
Referenced by eval().
topLeftCorner()
BlockDataset H5Object::topLeftCorner (unsigned numRows, unsigned numCols) const
Definition at line 119 of file H5Object.cpp.
References block().
Referenced by eval().
topRightCorner()
BlockDataset H5Object::topRightCorner (unsigned numRows, unsigned numCols) const
Definition at line 129 of file H5Object.cpp.
References block(), and cols().
Referenced by eval().
topRows()
BlockDataset H5Object::topRows (unsigned numRows) const
Definition at line 139 of file H5Object.cpp.
References block(), and cols().
Referenced by eval().
Friends And Related Function Documentation
muq::Utilities::AddChildren
H5Object muq::Utilities::AddChildren (std::shared_ptr< HDF5File > file, std::string const & path) friend
Member Data Documentation
attrs
AttributeList muq::Utilities::H5Object::attrs
Definition at line 184 of file H5Object.h.
children
std::map<std::string, H5Object> muq::Utilities::H5Object::children private
Definition at line 190 of file H5Object.h.
Referenced by muq::Utilities::AddChildren(), CreateDataset(), CreateGroup(), operator[](), and Print().
file
std::shared_ptr<HDF5File> muq::Utilities::H5Object::file
Definition at line 182 of file H5Object.h.
Referenced by block(), col(), cols(), CreateDataset(), CreateGroup(), Flush(), muq::Utilities::OpenFile(), operator()(), row(), rows(), and size().
isDataset
bool muq::Utilities::H5Object::isDataset private
Definition at line 192 of file H5Object.h.
Referenced by block(), col(), eval(), operator()(), operator=(), operator[](), and row().
path
std::string muq::Utilities::H5Object::path private
Definition at line 188 of file H5Object.h.
Referenced by block(), col(), cols(), CreateDataset(), CreateGroup(), eval(), operator()(), Print(), row(), rows(), and size().
The documentation for this class was generated from the following files:
/Users/andy/software/muq-private/MUQ/Utilities/HDF5/H5Object.h
/Users/andy/software/muq-private/modules/Utilities/src/HDF5/H5Object.cpp