MUQ: muq::Modeling::ODE Class Reference
muq::Modeling::ODE Class Reference
#include <ODE.h>
Detailed Description
Definition at line 8 of file ODE.h.
Public Member Functions
ODE (std::shared_ptr< WorkPiece > rhs, boost::property_tree::ptree const &pt, std::shared_ptr< AnyAlgebra > algebra=std::make_shared< AnyAlgebra >())
virtual ~ODE ()
Public Member Functions inherited from muq::Modeling::ODEBase
ODEBase (std::shared_ptr< WorkPiece > rhs, boost::property_tree::ptree const &pt, std::shared_ptr< AnyAlgebra > algebra)
virtual ~ODEBase ()
Public Member Functions inherited from muq::Modeling::WorkPiece
WorkPiece ()
Create a muq::Modeling::WorkPiece with no fixed number of inputs and outputs and variable input/output types.
WorkPiece (int const num, WorkPiece::Fix const fix=WorkPiece::Fix::Inputs)
Create a muq::Modeling::WorkPiece with either a fixed number of inputs or outputs and variable input/output types.
WorkPiece (int const numIns, int const numOuts)
Create a muq::Modeling::WorkPiece with a fixed number of inputs and outputs but variable input/output types.
WorkPiece (std::vector< std::string > const &types, WorkPiece::Fix const fix=WorkPiece::Fix::Inputs)
Create a muq::Modeling::WorkPiece with either a fixed number of inputs with specified types or a fixed number of outputs with specified types.
WorkPiece (std::map< unsigned int, std::string > const &types, WorkPiece::Fix const fix=WorkPiece::Fix::Inputs)
Create a muq::Modeling::WorkPiece where either some of the inputs have specified types or some of the outputs have specified types.
WorkPiece (std::map< unsigned int, std::string > const &types, int const num, WorkPiece::Fix const fixTypes=WorkPiece::Fix::Inputs, WorkPiece::Fix const fixNum=WorkPiece::Fix::Inputs)
Create a muq::Modeling::WorkPiece where either some of the inputs have specified types or some of the outputs have specified types and either the number of inputs or the number of outputs is fixed.
WorkPiece (std::vector< std::string > const &types, int const num)
Create a muq::Modeling::WorkPiece with a fixed number of inputs with specified types and a fixed number of outputs (of uknown type)
WorkPiece (int const num, std::vector< std::string > const &types)
Create a muq::Modeling::WorkPiece with a fixed number of outputs with specified types and a fixed number of inputs (of uknown type)
WorkPiece (std::map< unsigned int, std::string > const &inTypes, int const numIns, int const numOuts)
Create a muq::Modeling::WorkPiece where some of the inputs are known and we know the input and output numbers.
WorkPiece (int const numIns, std::map< unsigned int, std::string > const &outTypes, int const numOuts)
Create a muq::Modeling::WorkPiece where some of the outputs are known and we know the input and output numbers.
WorkPiece (std::vector< std::string > const &inTypes, std::vector< std::string > const &outTypes)
Create a muq::Modeling::WorkPiece with a fixed number of inputs and outputs with specified types.
WorkPiece (std::map< unsigned int, std::string > const &inTypes, std::vector< std::string > const &outTypes)
Create a muq::Modeling::WorkPiece where some of the inputs are known and all of the outputs have specified types.
WorkPiece (std::map< unsigned int, std::string > const &inTypes, int const num, std::vector< std::string > const &outTypes)
Create a muq::Modeling::WorkPiece where some of the inputs are known with a known number of inputs and all of the outputs have specified types.
WorkPiece (std::vector< std::string > const &inTypes, std::map< unsigned int, std::string > const &outTypes)
Create a muq::Modeling::WorkPiece where some of the outputs and all of the inputs have specified types.
WorkPiece (std::vector< std::string > const &inTypes, std::map< unsigned int, std::string > const &outTypes, int const num)
Create a muq::Modeling::WorkPiece where some of the outputs with a known number of outputs and all of the inputs have specified types.
WorkPiece (std::map< unsigned int, std::string > const &inTypes, std::map< unsigned int, std::string > const &outTypes)
Create a muq::Mdoeling::WorkPiece where some of the inputs and some of the outputs have specified types.
WorkPiece (std::map< unsigned int, std::string > const &inTypes, int const numIn, std::map< unsigned int, std::string > const &outTypes)
Create a muq::Mdoeling::WorkPiece where some of the inputs and some of the outputs have specified types with a fixed number of inputs.
WorkPiece (std::map< unsigned int, std::string > const &inTypes, std::map< unsigned int, std::string > const &outTypes, int const numOut)
Create a muq::Mdoeling::WorkPiece where some of the inputs and some of the outputs have specified types with a fixed number of outputs.
WorkPiece (std::map< unsigned int, std::string > const &inTypes, int const numIn, std::map< unsigned int, std::string > const &outTypes, int const numOut)
Create a muq::Mdoeling::WorkPiece where some of the inputs and some of the outputs have specified types with a fixed number of inputs and outputs.
virtual ~WorkPiece ()
Default destructor.
std::vector< boost::any > Evaluate (std::vector< boost::any > const &ins)
Evaluate this muq::Modeling::WorkPiece.
std::vector< boost::any > Evaluate (ref_vector< boost::any > const &ins)
Evaluate this muq::Modeling::WorkPiece using references to the inputs.
std::vector< boost::any > Evaluate ()
Evaluate this muq::Modeling::WorkPiece in the case that there are no inputs.
template<typename... Args>
std::vector< boost::any > Evaluate (Args... args)
Evalaute this muq::Modeling::WorkPiece using multiple arguments.
boost::any Jacobian (unsigned int const wrtIn, unsigned int const wrtOut, std::vector< boost::any > const &ins)
Evaluate the Jacobian of this muq::Modeling::WorkPiece using references to the inputs.
boost::any Jacobian (unsigned int const wrtIn, unsigned int const wrtOut, ref_vector< boost::any > const &ins)
Evaluate the Jacobian of this muq::Modeling::WorkPiece using references to the inputs.
template<typename... Args>
boost::any Jacobian (unsigned int const wrtIn, unsigned int const wrtOut, Args... args)
Evaluate the Jacobian of this muq::Modeling::WorkPiece using multiple arguments.
void JacobianByFD (unsigned int const wrtIn, unsigned int const wrtOut, ref_vector< boost::any > const &inputs, double const relTol=1.0e-4, const double minTol=1.0e-6)
Compute the Jacobian using finite differences.
boost::any JacobianAction (unsigned int const wrtIn, unsigned int const wrtOut, boost::any const &vec, std::vector< boost::any > const &ins)
Evaluate the action of the Jacobian of this muq::Modeling::WorkPiece using references to the inputs.
boost::any JacobianAction (unsigned int const wrtIn, unsigned int const wrtOut, boost::any const &vec, ref_vector< boost::any > const &ins)
Evaluate the action of the Jacobian of this muq::Modeling::WorkPiece using references to the inputs.
template<typename... Args>
boost::any JacobianAction (unsigned int const wrtIn, unsigned int const wrtOut, boost::any const &vec, Args... args)
Evaluate the action of the Jacobian of this muq::Modeling::WorkPiece using multiple arguments.
void JacobianActionByFD (unsigned int const wrtIn, unsigned int const wrtOut, boost::any const &vec, ref_vector< boost::any > const &input)
Compute the action of the Jacobian using finite differences.
boost::any JacobianTransposeAction (unsigned int const wrtIn, unsigned int const wrtOut, boost::any const &vec, std::vector< boost::any > const &ins)
Evaluate the action of the Jacobian transpose of this muq::Modeling::WorkPiece using references to the inputs.
boost::any JacobianTransposeAction (unsigned int const wrtIn, unsigned int const wrtOut, boost::any const &vec, ref_vector< boost::any > const &ins)
Evaluate the action of the Jacobian transpose of this muq::Modeling::WorkPiece using references to the inputs.
template<typename... Args>
boost::any JacobianTransposeAction (unsigned int const wrtIn, unsigned int const wrtOut, boost::any const &vec, Args... args)
Evaluate the action of the Jacobian transpose of this muq::Modeling::WorkPiece using multiple arguments.
void JacobianTransposeActionByFD (unsigned int const wrtIn, unsigned int const wrtOut, boost::any const &vec, ref_vector< boost::any > const &inputs)
Compute the action of the Jacobian transpose using finite differences.
std::string Name () const
Get the (unique) name of this work piece.
std::string InputType (unsigned int inputNum, bool const demangle=true) const
Get the input type (if we know it) for a specific input.
std::string OutputType (unsigned int outputNum, bool const demangle=true) const
Get the output type (if we know it) for a specific output.
std::map< unsigned int, std::string > OutputTypes () const
Get the output types.
std::map< unsigned int, std::string > InputTypes () const
Get the input types.
unsigned int ID () const
Get the unique ID number.
Additional Inherited Members
Public Attributes inherited from muq::Modeling::WorkPiece
int numInputs
The number of inputs.
int numOutputs
The number of outputs.
Constructor & Destructor Documentation
ODE()
ODE::ODE (std::shared_ptr< WorkPiece > rhs, boost::property_tree::ptree const & pt, std::shared_ptr< AnyAlgebra > algebra = std::make_shared<AnyAlgebra>())
The first input is the initial state (at \(t=0\)). It is also the first input to the right hand side muq::Modeling::WorkPiece. This must a N_Vector type (the vectors that Sundials uses).
The next set of inputs are the inputs to the right hand side muq::Modeling::WorkPiece. If the right hand side input takes 2 inputs besides the state, these correspond to inputs 2 and 3 of the muq::Modeling::ODEBase. Their types are known if the types are known by the rhs muq::Modeling::WorkPiece.
Any inputs after the right hand sides inputs are either doubles or vectors of doubles. The output type is the state at these times. For example, if the last three inputs (after the RHS inputs) were 2.0 and std::vector<double>({1.0, 2.0}) and 1.5 then there would be three outputs — the state at time 2.0, a vector of the state at times 1.0 and 2.0, and the state at time 1.5.
Parameters
[in] rhs The right hand side of the ODE
[in] pt A boost::property_tree::ptree with options/tolerances for the ODE integrator
[in] algebra A muq::Modeling::AnyAlgebra used to manipulate the state and input parameters (defaults to the MUQ default)
Definition at line 17 of file ODE.cpp.
~ODE()
ODE::~ODE () virtual
Definition at line 19 of file ODE.cpp.
Member Function Documentation
ForwardIntegration()
void ODE::ForwardIntegration (void * cvode_mem, N_Vector & state, ref_vector< boost::any > const & outputTimes) private
Integrate forward in time without computing derivative information.
Parameters
[in] cvode_mem The Sundials solver
[in,out] state The state — begins at initial state, ends at final state
[in] outputTimes The output times the user has requested
Definition at line 74 of file ODE.cpp.
References muq::Modeling::ODEBase::NextTime(), and muq::Modeling::ODEBase::TimeIndices().
Referenced by Integrate().
ForwardSensitivity()
void ODE::ForwardSensitivity (void * cvode_mem, N_Vector & state, unsigned int const paramSize, unsigned int const wrtIn, boost::any const & outputTimes, ref_vector< boost::any > const & rhsInputs, DerivativeMode const & mode, N_Vector const & vec) private
Integrate forward in time, computing derivative information.
Parameters
[in] cvode_mem The Sundials solver
[in,out] state The state — begins at initial state, ends at final state
[in] paramSize The size of the input parameter we are differenating wrt
[in] wrtIn We are computing the derivative with repsect to this parameter
[in] outputTimes The output times corresponding to the output we are differentiating
[in] rhsInputs The inputs to the right hand side
[in] mode Are we computing the Jacobian, Jacobian action, or Jacobian transpose action?
[in] vec The vector the Jacobian or its transpose is acting on at eact timestep
Definition at line 103 of file ODE.cpp.
References muq::Modeling::ODEBase::algebra, muq::Modeling::ODEBase::CheckFlag(), muq::Modeling::ODEBase::InitializeDerivative(), muq::Modeling::WorkPiece::numInputs, and muq::Modeling::ODEBase::SetUpSensitivity().
Referenced by Integrate().
Integrate()
void ODE::Integrate (ref_vector< boost::any > const & inputs, int const wrtIn = -1, int const wrtOut = -1, N_Vector const & vec = nullptr, DerivativeMode const & mode = DerivativeMode::Jac) private
Integrate forward in time, possibly keeping track fo forward sensitivities.
Parameters
[in] inputs The inputs to the right hand side and the output times
[in] wrtIn We are computing the derivative with repsect to this parameter
[in] wrtOut We are computing the derivative of this output
[in] vec The vector the Jacobian transpose is acting on at eact timestep
[in] mode Are we computing the Jacobian, Jacobian action, or Jacobian transpose action?
Definition at line 21 of file ODE.cpp.
References muq::Modeling::ODEBase::algebra, muq::Modeling::ODEBase::autonomous, muq::Modeling::ODEBase::CheckFlag(), muq::Modeling::ODEBase::ClearResults(), muq::Modeling::ODEBase::CreateSolverMemory(), FindPtreeParameters::data, muq::Modeling::ODEBase::DeepCopy(), ForwardIntegration(), ForwardSensitivity(), muq::Modeling::ODEBase::multiStep, muq::Modeling::WorkPiece::numInputs, muq::Modeling::ODEBase::rhs, and muq::Modeling::ODEBase::solveMethod.
Referenced by JacobianImpl(), and JacobianTransposeActionImpl().
JacobianImpl()
void ODE::JacobianImpl (unsigned int const wrtIn, unsigned int const wrtOut, ref_vector< boost::any > const & inputs) override private virtual
Integrate the ODE forward in time.
\(M\) inputs:
The first \(N\) are the inputs to muq::Modeling::ODE::rhs
The second -N \(are the times where we want to return the state (either vectors or scalars) </ul> @param[in] inputs The inputs (see description) */ virtual void EvaluateImpl(ref_vector<boost::any> const& inputs) override; Evaluate the Jacobian of the state wrt each parameter /** Returns the Jacobian of the state with respect to an input parameter at each timestep. Returns a vector of Jacobians at each timestep if the output has more than one time. \) \(inputs: <ul> <li> The first \) \(are the inputs to muq::Modeling::ODE::rhs <li> The second \fM-N\) are the times where we want to return the state (either vectors or scalars)
Parameters
[in] wrtIn We are computing the derivative with repsect to this parameter
[in] wrtOut We are computing the derivative of this output
[in] inputs The inputs (see description)
Reimplemented from muq::Modeling::WorkPiece.
Definition at line 308 of file ODE.cpp.
References muq::Modeling::ODEBase::algebra, Integrate(), muq::Modeling::WorkPiece::JacobianActionImpl(), and muq::Modeling::WorkPiece::numInputs.
JacobianTransposeActionImpl()
void ODE::JacobianTransposeActionImpl (unsigned int const wrtIn, unsigned int const wrtOut, boost::any const & vec, ref_vector< boost::any > const & inputs) override private virtual
Evaluate the action of the Jacobian on a given vector wrt each parameter.
Returns the action of the Jacobian on a given vector with respect to an input parameter at each timestep. Returns a vector of Jacobians actions at each timestep if the output has more than one time.
\(M\) inputs:
The first \(N\) are the inputs to muq::Modeling::ODE::rhs
The second -N \(are the times where we want to return the state (either vectors or scalars) </ul> @param[in] wrtIn We are computing the derivative with repsect to this parameter @param[in] wrtOut We are computing the derivative of this output @param[in] vec The vector the Jacobian is acting on at eact timestep @param[in] inputs The inputs (see description) */ virtual void JacobianActionImpl(unsigned int const wrtIn, unsigned int const wrtOut, boost::any const& vec, ref_vector<boost::any> const& inputs) override; Evaluate the action of the Jacobian transpose on a given vector wrt each parameter /** Returns the action of the Jacobian transpose on a given vector with respect to an input parameter at each timestep. Returns a vector of Jacobian transpose actions at each timestep if the output has more than one time. \) \(inputs: <ul> <li> The first \) \(are the inputs to muq::Modeling::ODE::rhs <li> The second \fM-N\) are the times where we want to return the state (either vectors or scalars)
Parameters
[in] wrtIn We are computing the derivative with repsect to this parameter
[in] wrtOut We are computing the derivative of this output
[in] vec The vector the Jacobian transpose is acting on at eact timestep
[in] inputs The inputs (see description)
Reimplemented from muq::Modeling::WorkPiece.
Definition at line 325 of file ODE.cpp.
References Integrate().
SaveDerivative()
void ODE::SaveDerivative (unsigned int const ntimes, unsigned int const timeIndex, unsigned int const paramSize, unsigned int const wrtIn, N_Vector * sensState, N_Vector const & state, ref_vector< boost::any > rhsInputs, N_Vector const & vec, DerivativeMode const & mode) private
Save the derivative information.
Parameters
[in] ntimes The number of output times
[in] timeIndex Index of the output vector to save the current derivative information in
[in] paramSize The size of the input parameter we are differenating wrt
[in] wrtIn We are computing the derivative with repsect to this parameter
[in] sensState The Jacobian of the state (resulting from Sundials solver) — nullptr if we are not differentiating with respect to an input to the right hand side
[in] state The state — begins at initial state, ends at final state
[in] rhsInputs The inputs to the right hand side
[in] vec The vector the Jacobian or its transpose is acting on at eact timestep
[in] mode Are we computing the Jacobian, Jacobian action, or Jacobian transpose action?
Definition at line 160 of file ODE.cpp.
References muq::Modeling::WorkPiece::jacobian, muq::Modeling::WorkPiece::jacobianAction, muq::Modeling::WorkPiece::jacobianTransposeAction, SaveJacobian(), SaveJacobianAction(), and SaveJacobianTransposeAction().
SaveJacobian()
void ODE::SaveJacobian (DlsMat & jac, unsigned int const ncols, unsigned int const wrtIn, N_Vector * sensState, N_Vector const & state, ref_vector< boost::any > rhsInputs) const private
Save the Jacobian.
Parameters
[out] jac The Jacobian at this time step
[in] ncols The number of columns in the Jacobian
[in] wrtIn We are computing the derivative with repsect to this parameter
[in] sensState The Jacobian of the state (resulting from Sundials solver) — nullptr if we are not differentiating with respect to an input to the right hand side
[in] state The state — begins at initial state, ends at final state
[in] rhsInputs The inputs to the right hand side
Definition at line 265 of file ODE.cpp.
References muq::Modeling::ODEBase::rhs.
Referenced by SaveDerivative().
SaveJacobianAction()
void ODE::SaveJacobianAction (N_Vector & jacAct, unsigned int const ncols, unsigned int const wrtIn, N_Vector * sensState, N_Vector const & state, ref_vector< boost::any > rhsInputs, N_Vector const & vec) const private
Save the action of the Jacobian.
Parameters
[out] jacAct The action of the Jacobian at this time step
[in] ncols The number of columns in the Jacobian
[in] wrtIn We are computing the derivative with repsect to this parameter
[in] sensState The Jacobian of the state (resulting from Sundials solver) — nullptr if we are not differentiating with respect to an input to the right hand side
[in] state The state — begins at initial state, ends at final state
[in] rhsInputs The inputs to the right hand side
[in] vec The vector the Jacobian is acting on at eact timestep
Definition at line 198 of file ODE.cpp.
References muq::Modeling::ODEBase::rhs.
Referenced by SaveDerivative().
SaveJacobianTransposeAction()
void ODE::SaveJacobianTransposeAction (N_Vector & jacTransAct, unsigned int const ncols, unsigned int const wrtIn, N_Vector * sensState, N_Vector const & state, ref_vector< boost::any > rhsInputs, N_Vector const & vec) const private
Save the action of the Jacobian transpose.
Parameters
[out] jacTransAct The action of the Jacobian transpose at this time step
[in] ncols The number of columns in the Jacobian
[in] wrtIn We are computing the derivative with repsect to this parameter
[in] sensState The Jacobian of the state (resulting from Sundials solver) — nullptr if we are not differentiating with respect to an input to the right hand side
[in] state The state — begins at initial state, ends at final state
[in] rhsInputs The inputs to the right hand side
[in] vec The vector the Jacobian transpose is acting on at eact timestep
Definition at line 233 of file ODE.cpp.
References muq::Modeling::ODEBase::rhs.
Referenced by SaveDerivative().
The documentation for this class was generated from the following files:
/Users/andy/software/muq-private/MUQ/Modeling/ODE.h
/Users/andy/software/muq-private/modules/Modeling/src/ODE.cpp