MUQ: muq::Modeling::AnyAlgebra Class Reference
muq::Modeling::AnyAlgebra Class Reference
Implement a generic way to do algebric operations on boost::any's.
#include <AnyAlgebra.h>
Detailed Description
Implement a generic way to do algebric operations on boost::any's.
Definition at line 23 of file AnyAlgebra.h.
Public Member Functions
AnyAlgebra ()
Default constructor.
unsigned int VectorDimensionBase (boost::any const &vec) const
The dimension of a vector.
boost::any AccessElementBase (unsigned int i, boost::any const &vec) const
Access an element of a vector.
boost::any IdentityBase (std::reference_wrapper< const boost::any > const &in) const
Compute an identity object for boost::any.
boost::any AddBase (std::reference_wrapper< const boost::any > const &in0, std::reference_wrapper< const boost::any > const &in1) const
Add two objects together.
boost::any MultiplyBase (std::reference_wrapper< const boost::any > const &in0, std::reference_wrapper< const boost::any > const &in1) const
Multiply two objects.
Constructor & Destructor Documentation
AnyAlgebra()
AnyAlgebra::AnyAlgebra ()
Default constructor.
Definition at line 5 of file AnyAlgebra.cpp.
Member Function Documentation
AccessElement()
boost::any AnyAlgebra::AccessElement (unsigned int i, boost::any const & vec) const private virtual
Access an element of a vector.
MUQ automatically checks for some common input types. However, the user may need to overload this function for special types.
Parameters
[in] i We want to access the \(i^{th}\) element of a vector
[in] vec The vector whose data we want to access
Returns
The \(i^{th}\) element of the vector
Definition at line 126 of file AnyAlgebra.cpp.
Referenced by AccessElementBase().
AccessElementBase()
boost::any AnyAlgebra::AccessElementBase (unsigned int i, boost::any const & vec) const
Access an element of a vector.
The return type is whatever the elements of the vector are (doubles, ints, ect ...)
Parameters
[in] i We want to access the \(i^{th}\) element of a vector
[in] vec The vector whose data we want to access
Returns
The \(i^{th}\) element of the vector
Definition at line 57 of file AnyAlgebra.cpp.
References AccessElement(), doubleType, eigenVec2Type, eigenVec3Type, eigenVec4Type, and eigenVecType.
Add()
boost::any AnyAlgebra::Add (std::reference_wrapper< const boost::any > const & in0, std::reference_wrapper< const boost::any > const & in1) const private virtual
Add two objects together.
MUQ automatically checks for some common pairs. However, the user may need to overload this function for special types.
Parameters
[in] in0 The first input
[in] in1 The second input
Returns
The addition of in0 and in1 (in0+in1)
Definition at line 201 of file AnyAlgebra.cpp.
Referenced by AddBase().
AddBase()
boost::any AnyAlgebra::AddBase (std::reference_wrapper< const boost::any > const & in0, std::reference_wrapper< const boost::any > const & in1) const
Add two objects together.
Parameters
[in] in0 The first input
[in] in1 The second input
Returns
The addition of in0 and in1 (in0+in1)
Definition at line 160 of file AnyAlgebra.cpp.
References Add(), doubleType, eigenMatType, eigenVecType, and noneType.
Identity()
boost::any AnyAlgebra::Identity (std::reference_wrapper< const boost::any > const & in) const private virtual
Compute an identity object for boost::any.
MUQ automatically checks for some common input types. However, the user may need to overload this function for special types.
Parameters
[in] in The input — its type and size determines the return type and size
Returns
An identity of some type
Definition at line 151 of file AnyAlgebra.cpp.
Referenced by IdentityBase().
IdentityBase()
boost::any AnyAlgebra::IdentityBase (std::reference_wrapper< const boost::any > const & in) const
Compute an identity object for boost::any.
For example, if the underlying type is a double this would return 1.0, if the underlying type is an Eigen::VectorXd this would return Eigen::MatrixXd::Zero(N).
Parameters
[in] in The input — its type and size determines the return type and size
Returns
An identity of some type
Definition at line 135 of file AnyAlgebra.cpp.
References doubleType, eigenVecType, and Identity().
Multiply()
boost::any AnyAlgebra::Multiply (std::reference_wrapper< const boost::any > const & in, std::reference_wrapper< const boost::any > const & out) const private
Multiply two objects.
MUQ automatically checks for some common pairs. However, the user may need to overload this function for special types.
Parameters
[in] in0 The first input
[in] in1 The second input
Returns
The multiplication of in0 and in1 (in0*in1) — order matters!
Definition at line 247 of file AnyAlgebra.cpp.
Referenced by MultiplyBase().
MultiplyBase()
boost::any AnyAlgebra::MultiplyBase (std::reference_wrapper< const boost::any > const & in0, std::reference_wrapper< const boost::any > const & in1) const
Multiply two objects.
Parameters
[in] in0 The first input
[in] in1 The second input
Returns
The multiplication of in0 and in1 (in0*in1) — order matters!
Definition at line 210 of file AnyAlgebra.cpp.
References doubleType, eigenMatType, and Multiply().
VectorDimension()
unsigned int AnyAlgebra::VectorDimension (boost::any const & vec) const private virtual
The dimension of a vector.
MUQ automatically checks for some common input types. However, the user may need to overload this function for special types.
Parameters
[in] vec We need the size/dimension of this vector
Returns
The dimension of the input vector
Definition at line 48 of file AnyAlgebra.cpp.
Referenced by VectorDimensionBase().
VectorDimensionBase()
unsigned int AnyAlgebra::VectorDimensionBase (boost::any const & vec) const
The dimension of a vector.
Parameters
[in] vec We need the size/dimension of this vector
Returns
The dimension of the input vector
Definition at line 7 of file AnyAlgebra.cpp.
References doubleType, eigenVec2Type, eigenVec3Type, eigenVec4Type, eigenVecType, and VectorDimension().
Member Data Documentation
doubleType
const std::string muq::Modeling::AnyAlgebra::doubleType = typeid(double).name() private
The name of a double.
Definition at line 130 of file AnyAlgebra.h.
Referenced by AccessElementBase(), AddBase(), IdentityBase(), MultiplyBase(), and VectorDimensionBase().
eigenMatType
const std::string muq::Modeling::AnyAlgebra::eigenMatType = typeid(Eigen::MatrixXd).name() private
The name of a Eigen::MatrixXd.
Definition at line 127 of file AnyAlgebra.h.
Referenced by AddBase(), and MultiplyBase().
eigenVec2Type
const std::string muq::Modeling::AnyAlgebra::eigenVec2Type = typeid(Eigen::Vector2d).name() private
The name of a (2 dimensional) Eigen::Vector2d.
Definition at line 115 of file AnyAlgebra.h.
Referenced by AccessElementBase(), and VectorDimensionBase().
eigenVec3Type
const std::string muq::Modeling::AnyAlgebra::eigenVec3Type = typeid(Eigen::Vector3d).name() private
The name of a (3 dimensional) Eigen::Vector3d.
Definition at line 118 of file AnyAlgebra.h.
Referenced by AccessElementBase(), and VectorDimensionBase().
eigenVec4Type
const std::string muq::Modeling::AnyAlgebra::eigenVec4Type = typeid(Eigen::Vector4d).name() private
The name of a (4 dimensional) Eigen::Vector4d.
Definition at line 121 of file AnyAlgebra.h.
Referenced by AccessElementBase(), and VectorDimensionBase().
eigenVecType
const std::string muq::Modeling::AnyAlgebra::eigenVecType = typeid(Eigen::VectorXd).name() private
The name of a Eigen::VectorXd.
Definition at line 124 of file AnyAlgebra.h.
Referenced by AccessElementBase(), AddBase(), IdentityBase(), and VectorDimensionBase().
noneType
const std::string muq::Modeling::AnyAlgebra::noneType = typeid(boost::none).name() private
The name of a boost::none.
Definition at line 133 of file AnyAlgebra.h.
Referenced by AddBase().
The documentation for this class was generated from the following files:
/Users/andy/software/muq-private/MUQ/Modeling/AnyAlgebra.h
/Users/andy/software/muq-private/modules/Modeling/src/AnyAlgebra.cpp