MUQ: muq::Modeling::ODEBase Class Reference
muq::Modeling::ODEBase Class Reference
A bass class to integrate ODE's.
#include <ODEBase.h>
Detailed Description
A bass class to integrate ODE's.
Definition at line 14 of file ODEBase.h.
Public Member Functions
ODEBase (std::shared_ptr< WorkPiece > rhs, boost::property_tree::ptree const &pt, std::shared_ptr< AnyAlgebra > algebra)
virtual ~ODEBase ()
Public Member Functions inherited from muq::Modeling::WorkPiece
WorkPiece ()
Create a muq::Modeling::WorkPiece with no fixed number of inputs and outputs and variable input/output types.
WorkPiece (int const num, WorkPiece::Fix const fix=WorkPiece::Fix::Inputs)
Create a muq::Modeling::WorkPiece with either a fixed number of inputs or outputs and variable input/output types.
WorkPiece (int const numIns, int const numOuts)
Create a muq::Modeling::WorkPiece with a fixed number of inputs and outputs but variable input/output types.
WorkPiece (std::vector< std::string > const &types, WorkPiece::Fix const fix=WorkPiece::Fix::Inputs)
Create a muq::Modeling::WorkPiece with either a fixed number of inputs with specified types or a fixed number of outputs with specified types.
WorkPiece (std::map< unsigned int, std::string > const &types, WorkPiece::Fix const fix=WorkPiece::Fix::Inputs)
Create a muq::Modeling::WorkPiece where either some of the inputs have specified types or some of the outputs have specified types.
WorkPiece (std::map< unsigned int, std::string > const &types, int const num, WorkPiece::Fix const fixTypes=WorkPiece::Fix::Inputs, WorkPiece::Fix const fixNum=WorkPiece::Fix::Inputs)
Create a muq::Modeling::WorkPiece where either some of the inputs have specified types or some of the outputs have specified types and either the number of inputs or the number of outputs is fixed.
WorkPiece (std::vector< std::string > const &types, int const num)
Create a muq::Modeling::WorkPiece with a fixed number of inputs with specified types and a fixed number of outputs (of uknown type)
WorkPiece (int const num, std::vector< std::string > const &types)
Create a muq::Modeling::WorkPiece with a fixed number of outputs with specified types and a fixed number of inputs (of uknown type)
WorkPiece (std::map< unsigned int, std::string > const &inTypes, int const numIns, int const numOuts)
Create a muq::Modeling::WorkPiece where some of the inputs are known and we know the input and output numbers.
WorkPiece (int const numIns, std::map< unsigned int, std::string > const &outTypes, int const numOuts)
Create a muq::Modeling::WorkPiece where some of the outputs are known and we know the input and output numbers.
WorkPiece (std::vector< std::string > const &inTypes, std::vector< std::string > const &outTypes)
Create a muq::Modeling::WorkPiece with a fixed number of inputs and outputs with specified types.
WorkPiece (std::map< unsigned int, std::string > const &inTypes, std::vector< std::string > const &outTypes)
Create a muq::Modeling::WorkPiece where some of the inputs are known and all of the outputs have specified types.
WorkPiece (std::map< unsigned int, std::string > const &inTypes, int const num, std::vector< std::string > const &outTypes)
Create a muq::Modeling::WorkPiece where some of the inputs are known with a known number of inputs and all of the outputs have specified types.
WorkPiece (std::vector< std::string > const &inTypes, std::map< unsigned int, std::string > const &outTypes)
Create a muq::Modeling::WorkPiece where some of the outputs and all of the inputs have specified types.
WorkPiece (std::vector< std::string > const &inTypes, std::map< unsigned int, std::string > const &outTypes, int const num)
Create a muq::Modeling::WorkPiece where some of the outputs with a known number of outputs and all of the inputs have specified types.
WorkPiece (std::map< unsigned int, std::string > const &inTypes, std::map< unsigned int, std::string > const &outTypes)
Create a muq::Mdoeling::WorkPiece where some of the inputs and some of the outputs have specified types.
WorkPiece (std::map< unsigned int, std::string > const &inTypes, int const numIn, std::map< unsigned int, std::string > const &outTypes)
Create a muq::Mdoeling::WorkPiece where some of the inputs and some of the outputs have specified types with a fixed number of inputs.
WorkPiece (std::map< unsigned int, std::string > const &inTypes, std::map< unsigned int, std::string > const &outTypes, int const numOut)
Create a muq::Mdoeling::WorkPiece where some of the inputs and some of the outputs have specified types with a fixed number of outputs.
WorkPiece (std::map< unsigned int, std::string > const &inTypes, int const numIn, std::map< unsigned int, std::string > const &outTypes, int const numOut)
Create a muq::Mdoeling::WorkPiece where some of the inputs and some of the outputs have specified types with a fixed number of inputs and outputs.
virtual ~WorkPiece ()
Default destructor.
std::vector< boost::any > Evaluate (std::vector< boost::any > const &ins)
Evaluate this muq::Modeling::WorkPiece.
std::vector< boost::any > Evaluate (ref_vector< boost::any > const &ins)
Evaluate this muq::Modeling::WorkPiece using references to the inputs.
std::vector< boost::any > Evaluate ()
Evaluate this muq::Modeling::WorkPiece in the case that there are no inputs.
template<typename... Args>
std::vector< boost::any > Evaluate (Args... args)
Evalaute this muq::Modeling::WorkPiece using multiple arguments.
boost::any Jacobian (unsigned int const wrtIn, unsigned int const wrtOut, std::vector< boost::any > const &ins)
Evaluate the Jacobian of this muq::Modeling::WorkPiece using references to the inputs.
boost::any Jacobian (unsigned int const wrtIn, unsigned int const wrtOut, ref_vector< boost::any > const &ins)
Evaluate the Jacobian of this muq::Modeling::WorkPiece using references to the inputs.
template<typename... Args>
boost::any Jacobian (unsigned int const wrtIn, unsigned int const wrtOut, Args... args)
Evaluate the Jacobian of this muq::Modeling::WorkPiece using multiple arguments.
void JacobianByFD (unsigned int const wrtIn, unsigned int const wrtOut, ref_vector< boost::any > const &inputs, double const relTol=1.0e-4, const double minTol=1.0e-6)
Compute the Jacobian using finite differences.
boost::any JacobianAction (unsigned int const wrtIn, unsigned int const wrtOut, boost::any const &vec, std::vector< boost::any > const &ins)
Evaluate the action of the Jacobian of this muq::Modeling::WorkPiece using references to the inputs.
boost::any JacobianAction (unsigned int const wrtIn, unsigned int const wrtOut, boost::any const &vec, ref_vector< boost::any > const &ins)
Evaluate the action of the Jacobian of this muq::Modeling::WorkPiece using references to the inputs.
template<typename... Args>
boost::any JacobianAction (unsigned int const wrtIn, unsigned int const wrtOut, boost::any const &vec, Args... args)
Evaluate the action of the Jacobian of this muq::Modeling::WorkPiece using multiple arguments.
void JacobianActionByFD (unsigned int const wrtIn, unsigned int const wrtOut, boost::any const &vec, ref_vector< boost::any > const &input)
Compute the action of the Jacobian using finite differences.
boost::any JacobianTransposeAction (unsigned int const wrtIn, unsigned int const wrtOut, boost::any const &vec, std::vector< boost::any > const &ins)
Evaluate the action of the Jacobian transpose of this muq::Modeling::WorkPiece using references to the inputs.
boost::any JacobianTransposeAction (unsigned int const wrtIn, unsigned int const wrtOut, boost::any const &vec, ref_vector< boost::any > const &ins)
Evaluate the action of the Jacobian transpose of this muq::Modeling::WorkPiece using references to the inputs.
template<typename... Args>
boost::any JacobianTransposeAction (unsigned int const wrtIn, unsigned int const wrtOut, boost::any const &vec, Args... args)
Evaluate the action of the Jacobian transpose of this muq::Modeling::WorkPiece using multiple arguments.
void JacobianTransposeActionByFD (unsigned int const wrtIn, unsigned int const wrtOut, boost::any const &vec, ref_vector< boost::any > const &inputs)
Compute the action of the Jacobian transpose using finite differences.
std::string Name () const
Get the (unique) name of this work piece.
std::string InputType (unsigned int inputNum, bool const demangle=true) const
Get the input type (if we know it) for a specific input.
std::string OutputType (unsigned int outputNum, bool const demangle=true) const
Get the output type (if we know it) for a specific output.
std::map< unsigned int, std::string > OutputTypes () const
Get the output types.
std::map< unsigned int, std::string > InputTypes () const
Get the input types.
unsigned int ID () const
Get the unique ID number.
Additional Inherited Members
Public Attributes inherited from muq::Modeling::WorkPiece
int numInputs
The number of inputs.
int numOutputs
The number of outputs.
Member Enumeration Documentation
DerivativeMode
enum muq::Modeling::ODEBase::DerivativeMode protected
Are we computing the Jacobian, the action of the Jacobian, or the action of the Jacobian transpose.
Enumerator
Jac
The Jacobian.
JacAction
The action of the Jacobian.
JacTransAction
The action of the Jacobian transpose.
Definition at line 71 of file ODEBase.h.
LinearSolver
enum muq::Modeling::ODEBase::LinearSolver protected
Which linear solver should we use?
Enumerator
Dense
Dense solver.
SPGMR
SPGMR.
SPBCG
SPBCG.
SPTFQMR
SPTFQMR.
Definition at line 206 of file ODEBase.h.
Constructor & Destructor Documentation
ODEBase()
ODEBase::ODEBase (std::shared_ptr< WorkPiece > rhs, boost::property_tree::ptree const & pt, std::shared_ptr< AnyAlgebra > algebra)
The first input is the initial state (at \(t=0\)). It is also the first input to the right hand side muq::Modeling::WorkPiece. This must a N_Vector type (the vectors that Sundials uses).
The next set of inputs are the inputs to the right hand side muq::Modeling::WorkPiece. If the right hand side input takes 2 inputs besides the state, these correspond to inputs 2 and 3 of the muq::Modeling::ODEBase. Their types are known if the types are known by the rhs muq::Modeling::WorkPiece.
Additional inputs depend on which child inherits from muq::Modeling::ODEBase
Parameters options (for boost::property_tree::ptree):
The multistep method (ODESolver.MultistepMethod)
BDF: Backward differentiation formulas (BDF) linear mutlistep method (Default)
Adams: Adams-Moulton linear multistep method (for nonstiff problems)
The linear solver (ODESolver.LinearSolver)
Dense: Dense linear system solve (default)
SPGMR
SPBCG
SPTFQMR
The nonlinear solver (ODESolver.NonlinearSolver)
Newton: Nonlinear system solution through Newton's method (Default)
Iter: Nonlinear system solution through functional iterations
The relative tolerance (ODESolver.RelativeTolerance)
Defaults to 1e-8
The absolute tolerance (ODESolver.AbsoluteTolerance)
Defaults to 1e-8
The maximum time step size (ODESolver.MaxStepSize)
Defaults to 1.0
Is the RHS autonomous? (ODESolver.Autonomous)
Defaults to true
Parameters
[in] rhs The right hand side of the ODE
[in] pt A boost::property_tree::ptree with options/tolerances for the ODE integrator
[in] algebra A muq::Modeling::AnyAlgebra used to manipulate the state and input parameters
Definition at line 15 of file ODEBase.cpp.
~ODEBase()
ODEBase::~ODEBase () virtual
Definition at line 50 of file ODEBase.cpp.
Member Function Documentation
CheckFlag()
bool ODEBase::CheckFlag (void * flagvalue, std::string const & funcname, unsigned int const opt) const protected
Check the return flag of a Sundials function.
Parameters
[in] flagvalue The value of the Sundials flag
[in] funcname The name of the Sundials function
[in] opt An option to determine how to check the flag, 0: check if flag is nullptr, 1: flag is an int, check if flag<0 (indicates Sundials error)
Returns
false: failure, true: success
Definition at line 80 of file ODEBase.cpp.
Referenced by CreateSolverMemory(), muq::Modeling::RootfindingIVP::FindRoot(), muq::Modeling::ODE::ForwardSensitivity(), InitializeState(), muq::Modeling::ODE::Integrate(), and SetUpSensitivity().
ClearJacobian()
void ODEBase::ClearJacobian () private
Clear the jacobian.
Definition at line 443 of file ODEBase.cpp.
References DlsMatName, muq::Modeling::WorkPiece::jacobian, and stdvecDlsMatName.
Referenced by ClearResults().
ClearJacobianAction()
void ODEBase::ClearJacobianAction () private
Clear the jacobianAction.
Definition at line 463 of file ODEBase.cpp.
References muq::Modeling::WorkPiece::jacobianAction, N_VectorName, and stdvecN_VectorName.
Referenced by ClearResults().
ClearJacobianTransposeAction()
void ODEBase::ClearJacobianTransposeAction () private
Clear the jacobianTransposeAction.
Definition at line 483 of file ODEBase.cpp.
References muq::Modeling::WorkPiece::jacobianTransposeAction, N_VectorName, and stdvecN_VectorName.
Referenced by ClearResults().
ClearOutputs()
void ODEBase::ClearOutputs () private
Clear the outputs.
Definition at line 422 of file ODEBase.cpp.
References N_VectorName, muq::Modeling::WorkPiece::outputs, and stdvecN_VectorName.
Referenced by ClearResults().
ClearResults()
void ODEBase::ClearResults () protected
Clear the outputs, jacobian, jacobianAction, and jacobianTransposeAction.
Definition at line 503 of file ODEBase.cpp.
References ClearJacobian(), ClearJacobianAction(), ClearJacobianTransposeAction(), and ClearOutputs().
Referenced by muq::Modeling::RootfindingIVP::FindRoot(), and muq::Modeling::ODE::Integrate().
CreateSolverMemory()
void ODEBase::CreateSolverMemory (void * cvode_mem, N_Vector const & state, std::shared_ptr< ODEData > data) const protected
Alloc memory and set up options for the Sundials solver.
Parameters
[in] cvode_mem The Sundials solver
[in] state The initial state
[in] data An object that holds the RHS inputs and can evaluate the RHS
Definition at line 123 of file ODEBase.cpp.
References abstol, CheckFlag(), ErrorHandler(), EvaluateRHS(), maxStepSize, reltol, RHSJacobian(), RHSJacobianAction(), and slvr.
Referenced by muq::Modeling::RootfindingIVP::FindRoot(), and muq::Modeling::ODE::Integrate().
DeepCopy()
void ODEBase::DeepCopy (N_Vector & copy, N_Vector const & orig) const protected
Copy the values of an N_Vector.
Parameters
[out] copy A new vector whose size and values are the same as orig
[in] orig An existing vector to be copied
Definition at line 263 of file ODEBase.cpp.
Referenced by muq::Modeling::RootfindingIVP::FindRoot(), and muq::Modeling::ODE::Integrate().
ErrorHandler()
void ODEBase::ErrorHandler (int error_code, const char * module, const char * function, char * msg, void * user_data) static protected
Deal with Sundials errors.
Sundials will call this function if it runs into a problem
Parameters
[in] error_code Sundials error code
[in] module The name of the CVODES module reporting the error
[in] function The name of the function in which the error occured
[in] msg The error message
[in] user_data A pointer to an muq::Modeling::ODEData
Definition at line 121 of file ODEBase.cpp.
Referenced by CreateSolverMemory().
EvaluateRHS()
int ODEBase::EvaluateRHS (realtype time, N_Vector state, N_Vector deriv, void * user_data) static protected
Evaluate the right hand side.
Parameters
[in] time The current time
[in] state The current state
[out] deriv The derivative of the state with respect to time
[in] user_data A pointer to an muq::Modeling::ODEData
Definition at line 182 of file ODEBase.cpp.
References muq::Modeling::ODEData::autonomous, FindPtreeParameters::data, muq::Modeling::ODEData::inputs, and muq::Modeling::ODEData::rhs.
Referenced by CreateSolverMemory().
ForwardSensitivityRHS()
int ODEBase::ForwardSensitivityRHS (int Ns, realtype time, N_Vector y, N_Vector ydot, N_Vector * ys, N_Vector * ySdot, void * user_data, N_Vector tmp1, N_Vector tmp2) static protected
Sundials uses this function to compute the derivative of the state at each timestep.
Parameters
[in] Ns The number of sensitivities
[in] time The current time
[in] y The current state
[in] ydot The derivative of the current state with respect to time
[in] ys
[in] ySdot The sensitivties
[in] user_data A pointer to an muq::Modeling::ODEData
Definition at line 322 of file ODEBase.cpp.
References FindPtreeParameters::data, muq::Modeling::ODEData::inputs, muq::Modeling::ODEData::rhs, and muq::Modeling::ODEData::wrtIn.
Referenced by SetUpSensitivity().
InitializeDerivative()
void ODEBase::InitializeDerivative (unsigned int const ntimes, unsigned int const stateSize, unsigned int const paramSize, DerivativeMode const & mode) protected
Initialize the derivative output (muq::Modeling::WorkPiece::jacobian, muq::Modeling::WorkPiece::jacobianAction, or muq::Modeling::WorkPiece::jacobianTransposeAction)
Parameters
[in] ntimes The number of output times
[in] stateSize The size of the state
[in] paramSize The size of the input parameter we are differenating wrt
[in] mode Are we computing the Jacobian, Jacobian action, or Jacobian transpose action?
Definition at line 273 of file ODEBase.cpp.
References muq::Modeling::WorkPiece::jacobian, muq::Modeling::WorkPiece::jacobianAction, and muq::Modeling::WorkPiece::jacobianTransposeAction.
Referenced by muq::Modeling::RootfindingIVP::FindRoot(), and muq::Modeling::ODE::ForwardSensitivity().
InitializeState()
void ODEBase::InitializeState (N_Vector & state, boost::any const & ic, unsigned int const dim) const protected
Initialize the state vector to the initial conditions.
Parameters
[out] state The state vector (to be initialized)
[in] ic The initial conditions
[in] dim The dimension of the state
Definition at line 109 of file ODEBase.cpp.
References algebra, and CheckFlag().
NextTime()
bool ODEBase::NextTime (std::pair< double, int > & nextTime, std::vector< std::pair< unsigned int, unsigned int > > & timeIndices, ref_vector< boost::any > const & outputTimes) const protected
Compute the next time to integrate to.
Parameters
[out] nextTime first: the next time to integrate to, second: the output index
[out] timeIndices Each element corresponds to a vector of desired times, first: the current index of that vector, second: the size of that vector
[in] outputTimes We want the state at these times
Definition at line 386 of file ODEBase.cpp.
References algebra.
Referenced by muq::Modeling::RootfindingIVP::FindRoot(), and muq::Modeling::ODE::ForwardIntegration().
RHSJacobian()
int ODEBase::RHSJacobian (long int N, realtype time, N_Vector state, N_Vector rhs, DlsMat jac, void * user_data, N_Vector tmp1, N_Vector tmp2, N_Vector tmp3) static protected
Evaluate the Jacobian of the right hand side.
Parameters
[in] N
[in] time The current time
[in] state The current state
[in] rhs The derivative of the state with respect to time
[out] jac The Jacobian of the right hand side with respect to the current state
[in] user_data A pointer to an muq::Modeling::ODEData
[in] tmp1
[in] tmp2
[in] tmp3
Definition at line 234 of file ODEBase.cpp.
References muq::Modeling::ODEData::autonomous, FindPtreeParameters::data, muq::Modeling::ODEData::inputs, and muq::Modeling::ODEData::rhs.
Referenced by CreateSolverMemory().
RHSJacobianAction()
int ODEBase::RHSJacobianAction (N_Vector v, N_Vector Jv, realtype time, N_Vector state, N_Vector rhs, void * user_data, N_Vector tmp) static protected
Evaluate the action of the Jacobian of the right hand side.
Parameters
[in] v The vector the Jacobian is acting on
[out] Jv The action of the Jacobian on v
[in] time The current time
[in] state The current state
[in] rhs The derivative of the state with respect to time
[in] user_data A pointer to an muq::Modeling::ODEData
[in] tmp
Definition at line 211 of file ODEBase.cpp.
References muq::Modeling::ODEData::autonomous, FindPtreeParameters::data, muq::Modeling::ODEData::inputs, muq::Modeling::WorkPiece::jacobianAction, and muq::Modeling::ODEData::rhs.
Referenced by CreateSolverMemory().
SetInputOutputTypes()
void ODEBase::SetInputOutputTypes () private
Set the input and output types based on the rhs muq::Modeling::WorkPiece's.
Definition at line 52 of file ODEBase.cpp.
References autonomous, muq::Modeling::WorkPiece::inputTypes, and rhs.
SetUpSensitivity()
void ODEBase::SetUpSensitivity (void * cvode_mem, unsigned int const paramSize, N_Vector * sensState) const protected
Set up the solver for sensitivity information.
Parameters
[in] cvode_mem The Sundials solver
[in] paramSize The size of the input parameter we are differenating wrt
[in,out] sensState This will become the 'current' Jacobian
Definition at line 307 of file ODEBase.cpp.
References abstol, CheckFlag(), ForwardSensitivityRHS(), and reltol.
Referenced by muq::Modeling::RootfindingIVP::FindRoot(), and muq::Modeling::ODE::ForwardSensitivity().
TimeIndices()
std::vector< std::pair< unsigned int, unsigned int > > ODEBase::TimeIndices (ref_vector< boost::any > const & outputTimes) protected
The current index and size of each output vector.
[in] outputTimes The times the user has asked for
Returns
A vector of pairs — first: the current index of this output vector (starts at 0), second: the size of that output vector
Definition at line 358 of file ODEBase.cpp.
References algebra, and muq::Modeling::WorkPiece::outputs.
Referenced by muq::Modeling::RootfindingIVP::FindRoot(), and muq::Modeling::ODE::ForwardIntegration().
Member Data Documentation
abstol
const double muq::Modeling::ODEBase::abstol protected
The absolute tolerance.
Definition at line 231 of file ODEBase.h.
Referenced by CreateSolverMemory(), and SetUpSensitivity().
algebra
std::shared_ptr<AnyAlgebra> muq::Modeling::ODEBase::algebra protected
An algebra to manipulate the state and parameters.
Definition at line 221 of file ODEBase.h.
Referenced by muq::Modeling::RootfindingIVP::FindRoot(), muq::Modeling::ODE::ForwardSensitivity(), InitializeState(), muq::Modeling::ODE::Integrate(), muq::Modeling::ODE::JacobianImpl(), NextTime(), and TimeIndices().
autonomous
const bool muq::Modeling::ODEBase::autonomous protected
Is the RHS autonomous?
Definition at line 255 of file ODEBase.h.
Referenced by muq::Modeling::RootfindingIVP::FindRoot(), muq::Modeling::ODE::Integrate(), SetInputOutputTypes(), and muq::Modeling::RootfindingIVP::UpdateInputOutputTypes().
DlsMatName
const std::string muq::Modeling::ODEBase::DlsMatName = typeid(DlsMat).name() protected
DlsMat type name.
Definition at line 249 of file ODEBase.h.
Referenced by ClearJacobian().
linSolver
const std::string muq::Modeling::ODEBase::linSolver protected
Linear solver method.
Definition at line 224 of file ODEBase.h.
maxStepSize
const double muq::Modeling::ODEBase::maxStepSize protected
The maximum time step size.
Definition at line 234 of file ODEBase.h.
Referenced by CreateSolverMemory().
multiStep
int muq::Modeling::ODEBase::multiStep protected
Multistep method.
Definition at line 237 of file ODEBase.h.
Referenced by muq::Modeling::RootfindingIVP::FindRoot(), and muq::Modeling::ODE::Integrate().
N_VectorName
const std::string muq::Modeling::ODEBase::N_VectorName = typeid(N_Vector).name() protected
N_Vector type name.
Definition at line 243 of file ODEBase.h.
Referenced by ClearJacobianAction(), ClearJacobianTransposeAction(), and ClearOutputs().
reltol
const double muq::Modeling::ODEBase::reltol protected
The relative tolerance.
Definition at line 228 of file ODEBase.h.
Referenced by CreateSolverMemory(), and SetUpSensitivity().
rhs
std::shared_ptr<WorkPiece> muq::Modeling::ODEBase::rhs protected
The right hand side of the ODE.
Definition at line 218 of file ODEBase.h.
Referenced by muq::Modeling::RootfindingIVP::FindRoot(), muq::Modeling::ODE::Integrate(), muq::Modeling::RootfindingIVP::JacobianImpl(), muq::Modeling::ODE::SaveJacobian(), muq::Modeling::ODE::SaveJacobianAction(), muq::Modeling::ODE::SaveJacobianTransposeAction(), SetInputOutputTypes(), and muq::Modeling::RootfindingIVP::UpdateInputOutputTypes().
slvr
LinearSolver muq::Modeling::ODEBase::slvr protected
Definition at line 225 of file ODEBase.h.
Referenced by CreateSolverMemory().
solveMethod
int muq::Modeling::ODEBase::solveMethod protected
Nonlinear solver method.
Definition at line 240 of file ODEBase.h.
Referenced by muq::Modeling::RootfindingIVP::FindRoot(), and muq::Modeling::ODE::Integrate().
stdvecDlsMatName
const std::string muq::Modeling::ODEBase::stdvecDlsMatName = typeid(std::vector<DlsMat>).name() protected
std::vector<DlsMat> type name
Definition at line 252 of file ODEBase.h.
Referenced by ClearJacobian().
stdvecN_VectorName
const std::string muq::Modeling::ODEBase::stdvecN_VectorName = typeid(std::vector<N_Vector>).name() protected
std::vector<N_Vector> type name
Definition at line 246 of file ODEBase.h.
Referenced by ClearJacobianAction(), ClearJacobianTransposeAction(), and ClearOutputs().
The documentation for this class was generated from the following files:
/Users/andy/software/muq-private/MUQ/Modeling/ODEBase.h
/Users/andy/software/muq-private/modules/Modeling/src/ODEBase.cpp