MUQ: muq::Modeling::RootfindingIVP Class Reference
muq::Modeling::RootfindingIVP Class Reference
A rootfinding initial value problem — find the root of a function along an orbit of an ODE.
#include <RootfindingIVP.h>
Detailed Description
A rootfinding initial value problem — find the root of a function along an orbit of an ODE.
Definition at line 9 of file RootfindingIVP.h.
Public Member Functions
RootfindingIVP (std::shared_ptr< WorkPiece > rhs, std::shared_ptr< WorkPiece > root, boost::property_tree::ptree const &pt, std::shared_ptr< AnyAlgebra > algebra=std::make_shared< AnyAlgebra >())
virtual ~RootfindingIVP ()
Public Member Functions inherited from muq::Modeling::ODEBase
ODEBase (std::shared_ptr< WorkPiece > rhs, boost::property_tree::ptree const &pt, std::shared_ptr< AnyAlgebra > algebra)
virtual ~ODEBase ()
Public Member Functions inherited from muq::Modeling::WorkPiece
WorkPiece ()
Create a muq::Modeling::WorkPiece with no fixed number of inputs and outputs and variable input/output types.
WorkPiece (int const num, WorkPiece::Fix const fix=WorkPiece::Fix::Inputs)
Create a muq::Modeling::WorkPiece with either a fixed number of inputs or outputs and variable input/output types.
WorkPiece (int const numIns, int const numOuts)
Create a muq::Modeling::WorkPiece with a fixed number of inputs and outputs but variable input/output types.
WorkPiece (std::vector< std::string > const &types, WorkPiece::Fix const fix=WorkPiece::Fix::Inputs)
Create a muq::Modeling::WorkPiece with either a fixed number of inputs with specified types or a fixed number of outputs with specified types.
WorkPiece (std::map< unsigned int, std::string > const &types, WorkPiece::Fix const fix=WorkPiece::Fix::Inputs)
Create a muq::Modeling::WorkPiece where either some of the inputs have specified types or some of the outputs have specified types.
WorkPiece (std::map< unsigned int, std::string > const &types, int const num, WorkPiece::Fix const fixTypes=WorkPiece::Fix::Inputs, WorkPiece::Fix const fixNum=WorkPiece::Fix::Inputs)
Create a muq::Modeling::WorkPiece where either some of the inputs have specified types or some of the outputs have specified types and either the number of inputs or the number of outputs is fixed.
WorkPiece (std::vector< std::string > const &types, int const num)
Create a muq::Modeling::WorkPiece with a fixed number of inputs with specified types and a fixed number of outputs (of uknown type)
WorkPiece (int const num, std::vector< std::string > const &types)
Create a muq::Modeling::WorkPiece with a fixed number of outputs with specified types and a fixed number of inputs (of uknown type)
WorkPiece (std::map< unsigned int, std::string > const &inTypes, int const numIns, int const numOuts)
Create a muq::Modeling::WorkPiece where some of the inputs are known and we know the input and output numbers.
WorkPiece (int const numIns, std::map< unsigned int, std::string > const &outTypes, int const numOuts)
Create a muq::Modeling::WorkPiece where some of the outputs are known and we know the input and output numbers.
WorkPiece (std::vector< std::string > const &inTypes, std::vector< std::string > const &outTypes)
Create a muq::Modeling::WorkPiece with a fixed number of inputs and outputs with specified types.
WorkPiece (std::map< unsigned int, std::string > const &inTypes, std::vector< std::string > const &outTypes)
Create a muq::Modeling::WorkPiece where some of the inputs are known and all of the outputs have specified types.
WorkPiece (std::map< unsigned int, std::string > const &inTypes, int const num, std::vector< std::string > const &outTypes)
Create a muq::Modeling::WorkPiece where some of the inputs are known with a known number of inputs and all of the outputs have specified types.
WorkPiece (std::vector< std::string > const &inTypes, std::map< unsigned int, std::string > const &outTypes)
Create a muq::Modeling::WorkPiece where some of the outputs and all of the inputs have specified types.
WorkPiece (std::vector< std::string > const &inTypes, std::map< unsigned int, std::string > const &outTypes, int const num)
Create a muq::Modeling::WorkPiece where some of the outputs with a known number of outputs and all of the inputs have specified types.
WorkPiece (std::map< unsigned int, std::string > const &inTypes, std::map< unsigned int, std::string > const &outTypes)
Create a muq::Mdoeling::WorkPiece where some of the inputs and some of the outputs have specified types.
WorkPiece (std::map< unsigned int, std::string > const &inTypes, int const numIn, std::map< unsigned int, std::string > const &outTypes)
Create a muq::Mdoeling::WorkPiece where some of the inputs and some of the outputs have specified types with a fixed number of inputs.
WorkPiece (std::map< unsigned int, std::string > const &inTypes, std::map< unsigned int, std::string > const &outTypes, int const numOut)
Create a muq::Mdoeling::WorkPiece where some of the inputs and some of the outputs have specified types with a fixed number of outputs.
WorkPiece (std::map< unsigned int, std::string > const &inTypes, int const numIn, std::map< unsigned int, std::string > const &outTypes, int const numOut)
Create a muq::Mdoeling::WorkPiece where some of the inputs and some of the outputs have specified types with a fixed number of inputs and outputs.
virtual ~WorkPiece ()
Default destructor.
std::vector< boost::any > Evaluate (std::vector< boost::any > const &ins)
Evaluate this muq::Modeling::WorkPiece.
std::vector< boost::any > Evaluate (ref_vector< boost::any > const &ins)
Evaluate this muq::Modeling::WorkPiece using references to the inputs.
std::vector< boost::any > Evaluate ()
Evaluate this muq::Modeling::WorkPiece in the case that there are no inputs.
template<typename... Args>
std::vector< boost::any > Evaluate (Args... args)
Evalaute this muq::Modeling::WorkPiece using multiple arguments.
boost::any Jacobian (unsigned int const wrtIn, unsigned int const wrtOut, std::vector< boost::any > const &ins)
Evaluate the Jacobian of this muq::Modeling::WorkPiece using references to the inputs.
boost::any Jacobian (unsigned int const wrtIn, unsigned int const wrtOut, ref_vector< boost::any > const &ins)
Evaluate the Jacobian of this muq::Modeling::WorkPiece using references to the inputs.
template<typename... Args>
boost::any Jacobian (unsigned int const wrtIn, unsigned int const wrtOut, Args... args)
Evaluate the Jacobian of this muq::Modeling::WorkPiece using multiple arguments.
void JacobianByFD (unsigned int const wrtIn, unsigned int const wrtOut, ref_vector< boost::any > const &inputs, double const relTol=1.0e-4, const double minTol=1.0e-6)
Compute the Jacobian using finite differences.
boost::any JacobianAction (unsigned int const wrtIn, unsigned int const wrtOut, boost::any const &vec, std::vector< boost::any > const &ins)
Evaluate the action of the Jacobian of this muq::Modeling::WorkPiece using references to the inputs.
boost::any JacobianAction (unsigned int const wrtIn, unsigned int const wrtOut, boost::any const &vec, ref_vector< boost::any > const &ins)
Evaluate the action of the Jacobian of this muq::Modeling::WorkPiece using references to the inputs.
template<typename... Args>
boost::any JacobianAction (unsigned int const wrtIn, unsigned int const wrtOut, boost::any const &vec, Args... args)
Evaluate the action of the Jacobian of this muq::Modeling::WorkPiece using multiple arguments.
void JacobianActionByFD (unsigned int const wrtIn, unsigned int const wrtOut, boost::any const &vec, ref_vector< boost::any > const &input)
Compute the action of the Jacobian using finite differences.
boost::any JacobianTransposeAction (unsigned int const wrtIn, unsigned int const wrtOut, boost::any const &vec, std::vector< boost::any > const &ins)
Evaluate the action of the Jacobian transpose of this muq::Modeling::WorkPiece using references to the inputs.
boost::any JacobianTransposeAction (unsigned int const wrtIn, unsigned int const wrtOut, boost::any const &vec, ref_vector< boost::any > const &ins)
Evaluate the action of the Jacobian transpose of this muq::Modeling::WorkPiece using references to the inputs.
template<typename... Args>
boost::any JacobianTransposeAction (unsigned int const wrtIn, unsigned int const wrtOut, boost::any const &vec, Args... args)
Evaluate the action of the Jacobian transpose of this muq::Modeling::WorkPiece using multiple arguments.
void JacobianTransposeActionByFD (unsigned int const wrtIn, unsigned int const wrtOut, boost::any const &vec, ref_vector< boost::any > const &inputs)
Compute the action of the Jacobian transpose using finite differences.
std::string Name () const
Get the (unique) name of this work piece.
std::string InputType (unsigned int inputNum, bool const demangle=true) const
Get the input type (if we know it) for a specific input.
std::string OutputType (unsigned int outputNum, bool const demangle=true) const
Get the output type (if we know it) for a specific output.
std::map< unsigned int, std::string > OutputTypes () const
Get the output types.
std::map< unsigned int, std::string > InputTypes () const
Get the input types.
unsigned int ID () const
Get the unique ID number.
Additional Inherited Members
Public Attributes inherited from muq::Modeling::WorkPiece
int numInputs
The number of inputs.
int numOutputs
The number of outputs.
Constructor & Destructor Documentation
RootfindingIVP()
RootfindingIVP::RootfindingIVP (std::shared_ptr< WorkPiece > rhs, std::shared_ptr< WorkPiece > root, boost::property_tree::ptree const & pt, std::shared_ptr< AnyAlgebra > algebra = std::make_shared<AnyAlgebra>())
The first input is the initial state (at \(t=0\)). It is also the first input to the both right hand side and the root muq::Modeling::WorkPiece. The type must be the same in both sub-models (if it is known). This must a N_Vector type (the vectors that Sundials uses).
The next set of inputs are the inputs to the right hand side muq::Modeling::WorkPiece. If the right hand side input takes 2 inputs besides the state, these correspond to inputs 2 and 3 of the root finder. Their types are known if the types are known by the rhs muq::Modeling::WorkPiece.
The next set of inputs are the inputs to the root muq::Modeling::WorkPiece. If the root input takes 2 inputs besides the state, these correspond to inputs 4 and 5 of the root finder. Their types are known if the types are known by the rhs muq::Modeling::WorkPiece.
An optional final input is a vector of times to save the state. If the user gives muq::Modeling::RootfinderIVP this (optional) input it integrates until it finds a root, saving the state at each of these times.
The first output is the state at the root. This output has the same type as the first input to the right hand side and the root (if either is known). Note that the "the root" is the first state such that any one of the outputs from the root function is zero. It is boost::none if no root was found.
The second output is the time at which the root (first output) was obtained.
The third output exists if the user gives muq::Modeling::RootfinderIVP times to save the state (optional final input). This output is a vector — std::vector<StateType> — of states at the specified times.
Parameters options (for boost::property_tree::ptree):
All the parameter listed in muq::Modeling::ODEBase
The maximum number of steps (Rootfinder.MaxSteps)
Defaults to \(10^{10}\)
The maximum amount of time to integrate (Rootfinder.MaxTime)
Defaults to \(10^{3}\)
The maximum number of error tests (Rootfinder.MaxErrorTests)
Defaults to \(100\)
Parameters
[in] rhs A muq::Modeling::WorkPiece that evaluates the right hand side of the ODE
[in] root A muq::Modeling::WorkPiece whose outputs are double's — we integrate the ODE until we find the first root of one of these outputs
[in] pt A boost::property_tree::ptree with options/tolerances for the ODE integrator
[in] algebra A muq::Modeling::AnyAlgebra used to manipulate the state and input parameters (defaults to the MUQ default)
Definition at line 11 of file RootfindingIVP.cpp.
~RootfindingIVP()
RootfindingIVP::~RootfindingIVP () virtual
Definition at line 23 of file RootfindingIVP.cpp.
Member Function Documentation
EvaluateImpl()
void RootfindingIVP::EvaluateImpl (ref_vector< boost::any > const & inputs) override private virtual
Integrate the ODE until we find a root.
Parameters
[in] inputs The inputs (first: state, next group: rhs inputs, next group: root inputs, final: eval times (optional))
Implements muq::Modeling::WorkPiece.
Definition at line 162 of file RootfindingIVP.cpp.
References FindRoot().
EvaluateRoot()
int RootfindingIVP::EvaluateRoot (realtype t, N_Vector state, realtype * root, void * user_data) static private
Evaluate the root function.
Parameters
[in] t The current time
[in] state The state
[out] root The roots
[in] user_data A pointer to an muq::Modeling::ODEData
Definition at line 281 of file RootfindingIVP.cpp.
References FindPtreeParameters::data, muq::Modeling::ODEData::inputs, muq::Modeling::ODEData::rhs, and muq::Modeling::ODEData::root.
Referenced by FindRoot().
FindRoot()
Eigen::VectorXi RootfindingIVP::FindRoot (ref_vector< boost::any > const & inputs, int const wrtIn = -1, int const wrtOut = -1, DerivativeMode const & mode = DerivativeMode::Jac) private
Run the CVODES integrator.
Parameters
[in] inputs The inputs (first: state, next group: rhs inputs, next group: root inputs, final: eval times (optional))
[in] wrtIn We are computing the derivative with repsect to this parameter
[in] wrtOut We are computing the derivative of this output
[in] mode Are we computing the Jacobian, Jacobian action, or Jacobian transpose action?
Returns
A vector of length root->numOutputs, 0 indicates that output is not zero (no root found), 1 indicates that output is zero (a root was found)
Definition at line 25 of file RootfindingIVP.cpp.
References muq::Modeling::ODEBase::algebra, muq::Modeling::ODEBase::autonomous, muq::Modeling::ODEBase::CheckFlag(), muq::Modeling::ODEBase::ClearResults(), muq::Modeling::ODEBase::CreateSolverMemory(), FindPtreeParameters::data, muq::Modeling::ODEBase::DeepCopy(), EvaluateRoot(), muq::Modeling::ODEBase::InitializeDerivative(), maxErrorTests, maxSteps, muq::Modeling::ODEBase::multiStep, muq::Modeling::ODEBase::NextTime(), muq::Modeling::WorkPiece::numInputs, muq::Modeling::ODEBase::rhs, root, muq::Modeling::ODEBase::SetUpSensitivity(), muq::Modeling::ODEBase::solveMethod, and muq::Modeling::ODEBase::TimeIndices().
Referenced by EvaluateImpl(), and JacobianImpl().
JacobianImpl()
void RootfindingIVP::JacobianImpl (unsigned int const wrtIn, unsigned int const wrtOut, ref_vector< boost::any > const & inputs) override private virtual
Compute the Jacobian of the state at the root.
Parameters
[in] wrtIn We are computing the derivative with repsect to this parameter
[in] wrtOut We are computing the derivative of this output
[in] inputs The inputs (first: state, next group: rhs inputs, next group: root inputs, final: eval times (optional))
Reimplemented from muq::Modeling::WorkPiece.
Definition at line 167 of file RootfindingIVP.cpp.
References FindPtreeParameters::f, FindRoot(), muq::Modeling::WorkPiece::jacobian, muq::Modeling::WorkPiece::outputs, muq::Modeling::ODEBase::rhs, and root.
UpdateInputOutputTypes()
void RootfindingIVP::UpdateInputOutputTypes () private
Update the input and output types based on the rhs and root muq::Modeling::WorkPiece's.
Add the root input types to the inputs and set the second output type. Note the (optional) third output (the vector of state's at specified times) is std::vector<StateType> but we can't set this.
Definition at line 256 of file RootfindingIVP.cpp.
References muq::Modeling::ODEBase::autonomous, muq::Modeling::WorkPiece::inputTypes, muq::Modeling::WorkPiece::outputTypes, muq::Modeling::ODEBase::rhs, and root.
Member Data Documentation
maxErrorTests
const unsigned int muq::Modeling::RootfindingIVP::maxErrorTests private
The maximum number of error test failures.
Definition at line 103 of file RootfindingIVP.h.
Referenced by FindRoot().
maxSteps
const unsigned int muq::Modeling::RootfindingIVP::maxSteps private
The maximum number of steps the timesteper can take.
Definition at line 97 of file RootfindingIVP.h.
Referenced by FindRoot().
maxTime
const double muq::Modeling::RootfindingIVP::maxTime private
The maximum amount of time to integrate.
Definition at line 100 of file RootfindingIVP.h.
root
std::shared_ptr<WorkPiece> muq::Modeling::RootfindingIVP::root private
The root function.
Definition at line 94 of file RootfindingIVP.h.
Referenced by FindRoot(), JacobianImpl(), and UpdateInputOutputTypes().
The documentation for this class was generated from the following files:
/Users/andy/software/muq-private/MUQ/Modeling/RootfindingIVP.h
/Users/andy/software/muq-private/modules/Modeling/src/RootfindingIVP.cpp