MUQ: muq::Modeling::ConstantPiece Class Reference
muq::Modeling::ConstantPiece Class Reference
A muq::Modeling::WorkPiece with no inputs and known, constant outputs.
#include <ConstantPiece.h>
Detailed Description
A muq::Modeling::WorkPiece with no inputs and known, constant outputs.
Definition at line 9 of file ConstantPiece.h.
Public Member Functions
ConstantPiece (std::vector< boost::any > const &outs)
Create a muq::Modeling::ConstantPiece with the outputs given in a vector.
ConstantPiece ()
Create a muq::Modeling::ConstantPiece with no given outputs.
template<typename ith , typename... Args>
void SetOutputs (ith const &in, Args... args)
Create a muq::Modeling::ConstantPiece with the outputs given indivually.
Public Member Functions inherited from muq::Modeling::WorkPiece
WorkPiece ()
Create a muq::Modeling::WorkPiece with no fixed number of inputs and outputs and variable input/output types.
WorkPiece (int const num, WorkPiece::Fix const fix=WorkPiece::Fix::Inputs)
Create a muq::Modeling::WorkPiece with either a fixed number of inputs or outputs and variable input/output types.
WorkPiece (int const numIns, int const numOuts)
Create a muq::Modeling::WorkPiece with a fixed number of inputs and outputs but variable input/output types.
WorkPiece (std::vector< std::string > const &types, WorkPiece::Fix const fix=WorkPiece::Fix::Inputs)
Create a muq::Modeling::WorkPiece with either a fixed number of inputs with specified types or a fixed number of outputs with specified types.
WorkPiece (std::map< unsigned int, std::string > const &types, WorkPiece::Fix const fix=WorkPiece::Fix::Inputs)
Create a muq::Modeling::WorkPiece where either some of the inputs have specified types or some of the outputs have specified types.
WorkPiece (std::map< unsigned int, std::string > const &types, int const num, WorkPiece::Fix const fixTypes=WorkPiece::Fix::Inputs, WorkPiece::Fix const fixNum=WorkPiece::Fix::Inputs)
Create a muq::Modeling::WorkPiece where either some of the inputs have specified types or some of the outputs have specified types and either the number of inputs or the number of outputs is fixed.
WorkPiece (std::vector< std::string > const &types, int const num)
Create a muq::Modeling::WorkPiece with a fixed number of inputs with specified types and a fixed number of outputs (of uknown type)
WorkPiece (int const num, std::vector< std::string > const &types)
Create a muq::Modeling::WorkPiece with a fixed number of outputs with specified types and a fixed number of inputs (of uknown type)
WorkPiece (std::map< unsigned int, std::string > const &inTypes, int const numIns, int const numOuts)
Create a muq::Modeling::WorkPiece where some of the inputs are known and we know the input and output numbers.
WorkPiece (int const numIns, std::map< unsigned int, std::string > const &outTypes, int const numOuts)
Create a muq::Modeling::WorkPiece where some of the outputs are known and we know the input and output numbers.
WorkPiece (std::vector< std::string > const &inTypes, std::vector< std::string > const &outTypes)
Create a muq::Modeling::WorkPiece with a fixed number of inputs and outputs with specified types.
WorkPiece (std::map< unsigned int, std::string > const &inTypes, std::vector< std::string > const &outTypes)
Create a muq::Modeling::WorkPiece where some of the inputs are known and all of the outputs have specified types.
WorkPiece (std::map< unsigned int, std::string > const &inTypes, int const num, std::vector< std::string > const &outTypes)
Create a muq::Modeling::WorkPiece where some of the inputs are known with a known number of inputs and all of the outputs have specified types.
WorkPiece (std::vector< std::string > const &inTypes, std::map< unsigned int, std::string > const &outTypes)
Create a muq::Modeling::WorkPiece where some of the outputs and all of the inputs have specified types.
WorkPiece (std::vector< std::string > const &inTypes, std::map< unsigned int, std::string > const &outTypes, int const num)
Create a muq::Modeling::WorkPiece where some of the outputs with a known number of outputs and all of the inputs have specified types.
WorkPiece (std::map< unsigned int, std::string > const &inTypes, std::map< unsigned int, std::string > const &outTypes)
Create a muq::Mdoeling::WorkPiece where some of the inputs and some of the outputs have specified types.
WorkPiece (std::map< unsigned int, std::string > const &inTypes, int const numIn, std::map< unsigned int, std::string > const &outTypes)
Create a muq::Mdoeling::WorkPiece where some of the inputs and some of the outputs have specified types with a fixed number of inputs.
WorkPiece (std::map< unsigned int, std::string > const &inTypes, std::map< unsigned int, std::string > const &outTypes, int const numOut)
Create a muq::Mdoeling::WorkPiece where some of the inputs and some of the outputs have specified types with a fixed number of outputs.
WorkPiece (std::map< unsigned int, std::string > const &inTypes, int const numIn, std::map< unsigned int, std::string > const &outTypes, int const numOut)
Create a muq::Mdoeling::WorkPiece where some of the inputs and some of the outputs have specified types with a fixed number of inputs and outputs.
virtual ~WorkPiece ()
Default destructor.
std::vector< boost::any > Evaluate (std::vector< boost::any > const &ins)
Evaluate this muq::Modeling::WorkPiece.
std::vector< boost::any > Evaluate (ref_vector< boost::any > const &ins)
Evaluate this muq::Modeling::WorkPiece using references to the inputs.
std::vector< boost::any > Evaluate ()
Evaluate this muq::Modeling::WorkPiece in the case that there are no inputs.
template<typename... Args>
std::vector< boost::any > Evaluate (Args... args)
Evalaute this muq::Modeling::WorkPiece using multiple arguments.
boost::any Jacobian (unsigned int const wrtIn, unsigned int const wrtOut, std::vector< boost::any > const &ins)
Evaluate the Jacobian of this muq::Modeling::WorkPiece using references to the inputs.
boost::any Jacobian (unsigned int const wrtIn, unsigned int const wrtOut, ref_vector< boost::any > const &ins)
Evaluate the Jacobian of this muq::Modeling::WorkPiece using references to the inputs.
template<typename... Args>
boost::any Jacobian (unsigned int const wrtIn, unsigned int const wrtOut, Args... args)
Evaluate the Jacobian of this muq::Modeling::WorkPiece using multiple arguments.
void JacobianByFD (unsigned int const wrtIn, unsigned int const wrtOut, ref_vector< boost::any > const &inputs, double const relTol=1.0e-4, const double minTol=1.0e-6)
Compute the Jacobian using finite differences.
boost::any JacobianAction (unsigned int const wrtIn, unsigned int const wrtOut, boost::any const &vec, std::vector< boost::any > const &ins)
Evaluate the action of the Jacobian of this muq::Modeling::WorkPiece using references to the inputs.
boost::any JacobianAction (unsigned int const wrtIn, unsigned int const wrtOut, boost::any const &vec, ref_vector< boost::any > const &ins)
Evaluate the action of the Jacobian of this muq::Modeling::WorkPiece using references to the inputs.
template<typename... Args>
boost::any JacobianAction (unsigned int const wrtIn, unsigned int const wrtOut, boost::any const &vec, Args... args)
Evaluate the action of the Jacobian of this muq::Modeling::WorkPiece using multiple arguments.
void JacobianActionByFD (unsigned int const wrtIn, unsigned int const wrtOut, boost::any const &vec, ref_vector< boost::any > const &input)
Compute the action of the Jacobian using finite differences.
boost::any JacobianTransposeAction (unsigned int const wrtIn, unsigned int const wrtOut, boost::any const &vec, std::vector< boost::any > const &ins)
Evaluate the action of the Jacobian transpose of this muq::Modeling::WorkPiece using references to the inputs.
boost::any JacobianTransposeAction (unsigned int const wrtIn, unsigned int const wrtOut, boost::any const &vec, ref_vector< boost::any > const &ins)
Evaluate the action of the Jacobian transpose of this muq::Modeling::WorkPiece using references to the inputs.
template<typename... Args>
boost::any JacobianTransposeAction (unsigned int const wrtIn, unsigned int const wrtOut, boost::any const &vec, Args... args)
Evaluate the action of the Jacobian transpose of this muq::Modeling::WorkPiece using multiple arguments.
void JacobianTransposeActionByFD (unsigned int const wrtIn, unsigned int const wrtOut, boost::any const &vec, ref_vector< boost::any > const &inputs)
Compute the action of the Jacobian transpose using finite differences.
std::string Name () const
Get the (unique) name of this work piece.
std::string InputType (unsigned int inputNum, bool const demangle=true) const
Get the input type (if we know it) for a specific input.
std::string OutputType (unsigned int outputNum, bool const demangle=true) const
Get the output type (if we know it) for a specific output.
std::map< unsigned int, std::string > OutputTypes () const
Get the output types.
std::map< unsigned int, std::string > InputTypes () const
Get the input types.
unsigned int ID () const
Get the unique ID number.
Additional Inherited Members
Public Attributes inherited from muq::Modeling::WorkPiece
int numInputs
The number of inputs.
int numOutputs
The number of outputs.
Constructor & Destructor Documentation
ConstantPiece() [1/2]
ConstantPiece::ConstantPiece (std::vector< boost::any > const & outs)
Create a muq::Modeling::ConstantPiece with the outputs given in a vector.
Parameters
[in] outs The outputs
Definition at line 5 of file ConstantPiece.cpp.
References muq::Modeling::WorkPiece::clearOutputs, muq::Modeling::WorkPiece::numOutputs, and muq::Modeling::WorkPiece::outputs.
ConstantPiece() [2/2]
ConstantPiece::ConstantPiece ()
Create a muq::Modeling::ConstantPiece with no given outputs.
This creates a WorkPiece that takes no inputs and returns no outputs. The user can set the outputs to any thing after construction. The number of outputs is set to be variable.
Definition at line 14 of file ConstantPiece.cpp.
References muq::Modeling::WorkPiece::clearOutputs, muq::Modeling::WorkPiece::EvaluateImpl(), muq::Modeling::WorkPiece::outputs, muq::Modeling::WorkPiece::outputTypes, SetOutputs(), and muq::Modeling::WorkPiece::Types().
Member Function Documentation
SetOutputs()
template<typename ith , typename... Args> void ConstantPiece::SetOutputs (ith const & in, Args... args) inline
Create a muq::Modeling::ConstantPiece with the outputs given indivually.
The number of outputs is -1 (variable) even though we know the outputs.
Parameters
[in] in The \(i^{th}]f$ input @param[in] args The \)[i+1, N \(] outputs */ template<typename ith, typename... Args> ConstantPiece(ith const& in, Args... args) : ConstantPiece(args...) { // add this output to the begining of the output vector outputs.insert(outputs.begin(), in); // set the number of outputs numOutputs = outputs.size(); // set the output types outputTypes = Types(Types(outputs)); } Create a muq::Modeling::ConstantPiece with the outputs given indivually /** The number of outputs is -1 (variable) even though we know the outputs. @param[in] last the last output */ template<typename last> ConstantPiece(last const& in) : WorkPiece(0, WorkPiece::Fix::Inputs) { // the outputs will never change so we should not clear them clearOutputs = false; // add this output to the begining of the output vector outputs.insert(outputs.begin(), in); // set the number of outputs numOutputs = outputs.size(); // set the output types outputTypes = Types(Types(outputs)); } Set the outputs to be empty void SetOutputs(); Set the outputs /** @param[in] outs The new outputs */ void SetOutputs(std::vector<boost::any> const& outs); set the outputs with the outputs given indivually /** @param[in] in The \)^{th}]f$ input
[in] args The \([i+1, N\)] outputs
Definition at line 77 of file ConstantPiece.h.
References muq::Modeling::WorkPiece::EvaluateImpl().
Referenced by ConstantPiece().
The documentation for this class was generated from the following files:
/Users/andy/software/muq-private/MUQ/Modeling/ConstantPiece.h
/Users/andy/software/muq-private/modules/Modeling/src/ConstantPiece.cpp