MUQ: muq::Approximation::KernelBase Class Reference
muq::Approximation::KernelBase Class Reference abstract
Covariance Kernels
Base class for covariance kernels.
#include <CovarianceKernels.h>
Detailed Description
Base class for covariance kernels.
This class provides common functionality (such as computing Covariance matrices) for all covariance kernels. It uses the curiously recurring template pattern and requires that child classes implement the following functions
double operator(VectorType1,VectorType2)
unsigned GetDim()
unsigned GetCodim()
unsigned GetNumParams()
unsigned GetNumConstraints()
void SetParams(VectorType)
Definition at line 51 of file CovarianceKernels.h.
Public Member Functions
KernelBase (unsigned inputDimIn, unsigned coDimIn, unsigned numParamsIn)
KernelBase (unsigned inputDimIn, std::vector< unsigned > dimIndsIn, unsigned coDimIn, unsigned numParamsIn)
virtual ~KernelBase ()
virtual Eigen::MatrixXd Evaluate (Eigen::VectorXd const &x1, Eigen::VectorXd const &x2) const =0
virtual Eigen::MatrixXd BuildCovariance (Eigen::MatrixXd const &x) const =0
virtual Eigen::MatrixXd BuildCovariance (Eigen::MatrixXd const &x1, Eigen::MatrixXd const &x2) const =0
virtual void FillCovariance (Eigen::MatrixXd const &xs, Eigen::MatrixXd const &ys, Eigen::Ref< Eigen::MatrixXd > cov) const =0
virtual void FillCovariance (Eigen::MatrixXd const &xs, Eigen::Ref< Eigen::MatrixXd > cov) const =0
virtual void FillDerivativeMatrix (Eigen::MatrixXd const &xs, unsigned wrt, Eigen::Ref< Eigen::MatrixXd > derivs) const =0
virtual Eigen::MatrixXd GetDerivative (Eigen::VectorXd const &x1, Eigen::VectorXd const &x2, int wrt) const =0
virtual Eigen::MatrixXd GetParamBounds () const
virtual Eigen::VectorXd GetParams () const
virtual void SetParams (Eigen::VectorXd const &params)
virtual std::shared_ptr< KernelBase > Clone () const =0
Public Attributes
const std::vector< unsigned > dimInds
const unsigned inputDim
const unsigned coDim
const unsigned numParams
Constructor & Destructor Documentation
KernelBase() [1/2]
muq::Approximation::KernelBase::KernelBase (unsigned inputDimIn, unsigned coDimIn, unsigned numParamsIn) inline
Definition at line 57 of file CovarianceKernels.h.
KernelBase() [2/2]
muq::Approximation::KernelBase::KernelBase (unsigned inputDimIn, std::vector< unsigned > dimIndsIn, unsigned coDimIn, unsigned numParamsIn) inline
Definition at line 62 of file CovarianceKernels.h.
References coDim, and inputDim.
~KernelBase()
virtual muq::Approximation::KernelBase::~KernelBase () inline virtual
Definition at line 72 of file CovarianceKernels.h.
References BuildCovariance(), Evaluate(), FillCovariance(), FillDerivativeMatrix(), and GetDerivative().
Member Function Documentation
BuildCovariance() [1/2]
virtual Eigen::MatrixXd muq::Approximation::KernelBase::BuildCovariance (Eigen::MatrixXd const & x) const pure virtual
Implemented in muq::Approximation::KernelImpl< ChildType >, muq::Approximation::KernelImpl< SquaredExpKernel >, muq::Approximation::KernelImpl< ConcatenateKernel< KernelType1, KernelType2 > >, muq::Approximation::KernelImpl< WhiteNoiseKernel >, muq::Approximation::KernelImpl< LinearTransformKernel< KernelType > >, muq::Approximation::KernelImpl< SumKernel< LeftType, RightType > >, muq::Approximation::KernelImpl< CoregionalKernel >, muq::Approximation::KernelImpl< ConstantKernel >, and muq::Approximation::KernelImpl< ProductKernel< LeftType, RightType > >.
Referenced by ~KernelBase().
BuildCovariance() [2/2]
virtual Eigen::MatrixXd muq::Approximation::KernelBase::BuildCovariance (Eigen::MatrixXd const & x1, Eigen::MatrixXd const & x2) const pure virtual
Implemented in muq::Approximation::KernelImpl< ChildType >, muq::Approximation::KernelImpl< SquaredExpKernel >, muq::Approximation::KernelImpl< ConcatenateKernel< KernelType1, KernelType2 > >, muq::Approximation::KernelImpl< WhiteNoiseKernel >, muq::Approximation::KernelImpl< LinearTransformKernel< KernelType > >, muq::Approximation::KernelImpl< SumKernel< LeftType, RightType > >, muq::Approximation::KernelImpl< CoregionalKernel >, muq::Approximation::KernelImpl< ConstantKernel >, and muq::Approximation::KernelImpl< ProductKernel< LeftType, RightType > >.
BuildDimInds()
static std::vector<unsigned> muq::Approximation::KernelBase::BuildDimInds (unsigned dim) inline static private
Definition at line 121 of file CovarianceKernels.h.
Clone()
virtual std::shared_ptr<KernelBase> muq::Approximation::KernelBase::Clone () const pure virtual
Implemented in muq::Approximation::KernelImpl< ChildType >, muq::Approximation::KernelImpl< SquaredExpKernel >, muq::Approximation::KernelImpl< ConcatenateKernel< KernelType1, KernelType2 > >, muq::Approximation::KernelImpl< WhiteNoiseKernel >, muq::Approximation::KernelImpl< LinearTransformKernel< KernelType > >, muq::Approximation::KernelImpl< SumKernel< LeftType, RightType > >, muq::Approximation::KernelImpl< CoregionalKernel >, muq::Approximation::KernelImpl< ConstantKernel >, and muq::Approximation::KernelImpl< ProductKernel< LeftType, RightType > >.
Referenced by muq::Approximation::CoregionTie(), muq::Approximation::FillKernelVector(), and SetParams().
Evaluate()
virtual Eigen::MatrixXd muq::Approximation::KernelBase::Evaluate (Eigen::VectorXd const & x1, Eigen::VectorXd const & x2) const pure virtual
Implemented in muq::Approximation::KernelImpl< ChildType >, muq::Approximation::KernelImpl< SquaredExpKernel >, muq::Approximation::KernelImpl< ConcatenateKernel< KernelType1, KernelType2 > >, muq::Approximation::KernelImpl< WhiteNoiseKernel >, muq::Approximation::KernelImpl< LinearTransformKernel< KernelType > >, muq::Approximation::KernelImpl< SumKernel< LeftType, RightType > >, muq::Approximation::KernelImpl< CoregionalKernel >, muq::Approximation::KernelImpl< ConstantKernel >, and muq::Approximation::KernelImpl< ProductKernel< LeftType, RightType > >.
Referenced by ~KernelBase().
FillCovariance() [1/2]
virtual void muq::Approximation::KernelBase::FillCovariance (Eigen::MatrixXd const & xs, Eigen::MatrixXd const & ys, Eigen::Ref< Eigen::MatrixXd > cov) const pure virtual
Implemented in muq::Approximation::KernelImpl< ChildType >, muq::Approximation::KernelImpl< SquaredExpKernel >, muq::Approximation::KernelImpl< ConcatenateKernel< KernelType1, KernelType2 > >, muq::Approximation::KernelImpl< WhiteNoiseKernel >, muq::Approximation::KernelImpl< LinearTransformKernel< KernelType > >, muq::Approximation::KernelImpl< SumKernel< LeftType, RightType > >, muq::Approximation::KernelImpl< CoregionalKernel >, muq::Approximation::KernelImpl< ConstantKernel >, and muq::Approximation::KernelImpl< ProductKernel< LeftType, RightType > >.
Referenced by muq::Approximation::KernelImpl< ProductKernel< LeftType, RightType > >::BuildCovariance(), and ~KernelBase().
FillCovariance() [2/2]
virtual void muq::Approximation::KernelBase::FillCovariance (Eigen::MatrixXd const & xs, Eigen::Ref< Eigen::MatrixXd > cov) const pure virtual
Implemented in muq::Approximation::KernelImpl< ChildType >, muq::Approximation::KernelImpl< SquaredExpKernel >, muq::Approximation::KernelImpl< ConcatenateKernel< KernelType1, KernelType2 > >, muq::Approximation::KernelImpl< WhiteNoiseKernel >, muq::Approximation::KernelImpl< LinearTransformKernel< KernelType > >, muq::Approximation::KernelImpl< SumKernel< LeftType, RightType > >, muq::Approximation::KernelImpl< CoregionalKernel >, muq::Approximation::KernelImpl< ConstantKernel >, and muq::Approximation::KernelImpl< ProductKernel< LeftType, RightType > >.
FillDerivativeMatrix()
virtual void muq::Approximation::KernelBase::FillDerivativeMatrix (Eigen::MatrixXd const & xs, unsigned wrt, Eigen::Ref< Eigen::MatrixXd > derivs) const pure virtual
Implemented in muq::Approximation::KernelImpl< ChildType >, muq::Approximation::KernelImpl< SquaredExpKernel >, muq::Approximation::KernelImpl< ConcatenateKernel< KernelType1, KernelType2 > >, muq::Approximation::KernelImpl< WhiteNoiseKernel >, muq::Approximation::KernelImpl< LinearTransformKernel< KernelType > >, muq::Approximation::KernelImpl< SumKernel< LeftType, RightType > >, muq::Approximation::KernelImpl< CoregionalKernel >, muq::Approximation::KernelImpl< ConstantKernel >, and muq::Approximation::KernelImpl< ProductKernel< LeftType, RightType > >.
Referenced by ~KernelBase().
GetDerivative()
virtual Eigen::MatrixXd muq::Approximation::KernelBase::GetDerivative (Eigen::VectorXd const & x1, Eigen::VectorXd const & x2, int wrt) const pure virtual
Implemented in muq::Approximation::KernelImpl< ChildType >, muq::Approximation::KernelImpl< SquaredExpKernel >, muq::Approximation::KernelImpl< ConcatenateKernel< KernelType1, KernelType2 > >, muq::Approximation::KernelImpl< WhiteNoiseKernel >, muq::Approximation::KernelImpl< LinearTransformKernel< KernelType > >, muq::Approximation::KernelImpl< SumKernel< LeftType, RightType > >, muq::Approximation::KernelImpl< CoregionalKernel >, muq::Approximation::KernelImpl< ConstantKernel >, and muq::Approximation::KernelImpl< ProductKernel< LeftType, RightType > >.
Referenced by muq::Approximation::KernelImpl< ProductKernel< LeftType, RightType > >::GetDerivative(), and ~KernelBase().
GetParamBounds()
virtual Eigen::MatrixXd muq::Approximation::KernelBase::GetParamBounds () const inline virtual
Reimplemented in muq::Approximation::ConcatenateKernel< KernelType1, KernelType2 >, muq::Approximation::SumKernel< LeftType, RightType >, and muq::Approximation::ProductKernel< LeftType, RightType >.
Definition at line 95 of file CovarianceKernels.h.
References paramBounds.
GetParams()
virtual Eigen::VectorXd muq::Approximation::KernelBase::GetParams () const inline virtual
Reimplemented in muq::Approximation::LinearTransformKernel< KernelType >, muq::Approximation::ConcatenateKernel< KernelType1, KernelType2 >, muq::Approximation::SumKernel< LeftType, RightType >, muq::Approximation::ProductKernel< LeftType, RightType >, muq::Approximation::CoregionalKernel, muq::Approximation::ConstantKernel, muq::Approximation::SquaredExpKernel, and muq::Approximation::WhiteNoiseKernel.
Definition at line 101 of file CovarianceKernels.h.
SetParams()
virtual void muq::Approximation::KernelBase::SetParams (Eigen::VectorXd const & params) inline virtual
Reimplemented in muq::Approximation::LinearTransformKernel< KernelType >, muq::Approximation::ConcatenateKernel< KernelType1, KernelType2 >, muq::Approximation::SumKernel< LeftType, RightType >, muq::Approximation::ProductKernel< LeftType, RightType >, muq::Approximation::CoregionalKernel, muq::Approximation::ConstantKernel, muq::Approximation::SquaredExpKernel, and muq::Approximation::WhiteNoiseKernel.
Definition at line 103 of file CovarianceKernels.h.
References Clone().
Member Data Documentation
coDim
const unsigned muq::Approximation::KernelBase::coDim
Definition at line 112 of file CovarianceKernels.h.
Referenced by muq::Approximation::KernelImpl< ProductKernel< LeftType, RightType > >::BuildCovariance(), muq::Approximation::KernelImpl< ProductKernel< LeftType, RightType > >::Evaluate(), muq::Approximation::CoregionalKernel::EvaluateImpl(), muq::Approximation::SumKernel< LeftType, RightType >::EvaluateImpl(), muq::Approximation::KernelImpl< ProductKernel< LeftType, RightType > >::FillCovarianceImpl(), muq::Approximation::KernelImpl< ProductKernel< LeftType, RightType > >::FillDerivativeMatrixImpl(), muq::Approximation::KernelImpl< ProductKernel< LeftType, RightType > >::GetDerivative(), muq::Approximation::CoregionalKernel::GetDerivative(), muq::Approximation::CoregionalKernel::GetParams(), KernelBase(), and muq::Approximation::CoregionalKernel::SetParams().
dimInds
const std::vector<unsigned> muq::Approximation::KernelBase::dimInds
Definition at line 109 of file CovarianceKernels.h.
inputDim
const unsigned muq::Approximation::KernelBase::inputDim
Definition at line 111 of file CovarianceKernels.h.
Referenced by muq::Approximation::CoregionTie(), and KernelBase().
numParams
const unsigned muq::Approximation::KernelBase::numParams
Definition at line 113 of file CovarianceKernels.h.
Referenced by muq::Approximation::SquaredExpKernel::GetDerivative(), muq::Approximation::ProductKernel< LeftType, RightType >::GetDerivative(), muq::Approximation::SumKernel< LeftType, RightType >::GetDerivative(), muq::Approximation::ConcatenateKernel< KernelType1, KernelType2 >::GetDerivative(), muq::Approximation::ProductKernel< LeftType, RightType >::GetParamBounds(), muq::Approximation::SumKernel< LeftType, RightType >::GetParamBounds(), muq::Approximation::ConcatenateKernel< KernelType1, KernelType2 >::GetParamBounds(), muq::Approximation::ConstantKernel::GetParams(), muq::Approximation::CoregionalKernel::GetParams(), muq::Approximation::ProductKernel< LeftType, RightType >::GetParams(), muq::Approximation::SumKernel< LeftType, RightType >::GetParams(), and muq::Approximation::ConcatenateKernel< KernelType1, KernelType2 >::GetParams().
paramBounds
Eigen::MatrixXd muq::Approximation::KernelBase::paramBounds protected
Definition at line 117 of file CovarianceKernels.h.
Referenced by muq::Approximation::ConstantKernel::ConstantKernel(), GetParamBounds(), and muq::Approximation::WhiteNoiseKernel::WhiteNoiseKernel().
The documentation for this class was generated from the following file:
/Users/andy/software/muq-private/MUQ/Approximation/GaussianProcesses/CovarianceKernels.h