MUQ: muq::Modeling::WorkPiece Class Reference
muq::Modeling::WorkPiece Class Reference abstract
Base class for MUQ's modelling envronment.
#include <WorkPiece.h>
Detailed Description
Base class for MUQ's modelling envronment.
Definition at line 27 of file WorkPiece.h.
Public Member Functions
WorkPiece ()
Create a muq::Modeling::WorkPiece with no fixed number of inputs and outputs and variable input/output types.
WorkPiece (int const num, WorkPiece::Fix const fix=WorkPiece::Fix::Inputs)
Create a muq::Modeling::WorkPiece with either a fixed number of inputs or outputs and variable input/output types.
WorkPiece (int const numIns, int const numOuts)
Create a muq::Modeling::WorkPiece with a fixed number of inputs and outputs but variable input/output types.
WorkPiece (std::vector< std::string > const &types, WorkPiece::Fix const fix=WorkPiece::Fix::Inputs)
Create a muq::Modeling::WorkPiece with either a fixed number of inputs with specified types or a fixed number of outputs with specified types.
WorkPiece (std::map< unsigned int, std::string > const &types, WorkPiece::Fix const fix=WorkPiece::Fix::Inputs)
Create a muq::Modeling::WorkPiece where either some of the inputs have specified types or some of the outputs have specified types.
WorkPiece (std::map< unsigned int, std::string > const &types, int const num, WorkPiece::Fix const fixTypes=WorkPiece::Fix::Inputs, WorkPiece::Fix const fixNum=WorkPiece::Fix::Inputs)
Create a muq::Modeling::WorkPiece where either some of the inputs have specified types or some of the outputs have specified types and either the number of inputs or the number of outputs is fixed.
WorkPiece (std::vector< std::string > const &types, int const num)
Create a muq::Modeling::WorkPiece with a fixed number of inputs with specified types and a fixed number of outputs (of uknown type)
WorkPiece (int const num, std::vector< std::string > const &types)
Create a muq::Modeling::WorkPiece with a fixed number of outputs with specified types and a fixed number of inputs (of uknown type)
WorkPiece (std::map< unsigned int, std::string > const &inTypes, int const numIns, int const numOuts)
Create a muq::Modeling::WorkPiece where some of the inputs are known and we know the input and output numbers.
WorkPiece (int const numIns, std::map< unsigned int, std::string > const &outTypes, int const numOuts)
Create a muq::Modeling::WorkPiece where some of the outputs are known and we know the input and output numbers.
WorkPiece (std::vector< std::string > const &inTypes, std::vector< std::string > const &outTypes)
Create a muq::Modeling::WorkPiece with a fixed number of inputs and outputs with specified types.
WorkPiece (std::map< unsigned int, std::string > const &inTypes, std::vector< std::string > const &outTypes)
Create a muq::Modeling::WorkPiece where some of the inputs are known and all of the outputs have specified types.
WorkPiece (std::map< unsigned int, std::string > const &inTypes, int const num, std::vector< std::string > const &outTypes)
Create a muq::Modeling::WorkPiece where some of the inputs are known with a known number of inputs and all of the outputs have specified types.
WorkPiece (std::vector< std::string > const &inTypes, std::map< unsigned int, std::string > const &outTypes)
Create a muq::Modeling::WorkPiece where some of the outputs and all of the inputs have specified types.
WorkPiece (std::vector< std::string > const &inTypes, std::map< unsigned int, std::string > const &outTypes, int const num)
Create a muq::Modeling::WorkPiece where some of the outputs with a known number of outputs and all of the inputs have specified types.
WorkPiece (std::map< unsigned int, std::string > const &inTypes, std::map< unsigned int, std::string > const &outTypes)
Create a muq::Mdoeling::WorkPiece where some of the inputs and some of the outputs have specified types.
WorkPiece (std::map< unsigned int, std::string > const &inTypes, int const numIn, std::map< unsigned int, std::string > const &outTypes)
Create a muq::Mdoeling::WorkPiece where some of the inputs and some of the outputs have specified types with a fixed number of inputs.
WorkPiece (std::map< unsigned int, std::string > const &inTypes, std::map< unsigned int, std::string > const &outTypes, int const numOut)
Create a muq::Mdoeling::WorkPiece where some of the inputs and some of the outputs have specified types with a fixed number of outputs.
WorkPiece (std::map< unsigned int, std::string > const &inTypes, int const numIn, std::map< unsigned int, std::string > const &outTypes, int const numOut)
Create a muq::Mdoeling::WorkPiece where some of the inputs and some of the outputs have specified types with a fixed number of inputs and outputs.
virtual ~WorkPiece ()
Default destructor.
std::vector< boost::any > Evaluate (std::vector< boost::any > const &ins)
Evaluate this muq::Modeling::WorkPiece.
std::vector< boost::any > Evaluate (ref_vector< boost::any > const &ins)
Evaluate this muq::Modeling::WorkPiece using references to the inputs.
std::vector< boost::any > Evaluate ()
Evaluate this muq::Modeling::WorkPiece in the case that there are no inputs.
template<typename... Args>
std::vector< boost::any > Evaluate (Args... args)
Evalaute this muq::Modeling::WorkPiece using multiple arguments.
boost::any Jacobian (unsigned int const wrtIn, unsigned int const wrtOut, std::vector< boost::any > const &ins)
Evaluate the Jacobian of this muq::Modeling::WorkPiece using references to the inputs.
boost::any Jacobian (unsigned int const wrtIn, unsigned int const wrtOut, ref_vector< boost::any > const &ins)
Evaluate the Jacobian of this muq::Modeling::WorkPiece using references to the inputs.
template<typename... Args>
boost::any Jacobian (unsigned int const wrtIn, unsigned int const wrtOut, Args... args)
Evaluate the Jacobian of this muq::Modeling::WorkPiece using multiple arguments.
void JacobianByFD (unsigned int const wrtIn, unsigned int const wrtOut, ref_vector< boost::any > const &inputs, double const relTol=1.0e-4, const double minTol=1.0e-6)
Compute the Jacobian using finite differences.
boost::any JacobianAction (unsigned int const wrtIn, unsigned int const wrtOut, boost::any const &vec, std::vector< boost::any > const &ins)
Evaluate the action of the Jacobian of this muq::Modeling::WorkPiece using references to the inputs.
boost::any JacobianAction (unsigned int const wrtIn, unsigned int const wrtOut, boost::any const &vec, ref_vector< boost::any > const &ins)
Evaluate the action of the Jacobian of this muq::Modeling::WorkPiece using references to the inputs.
template<typename... Args>
boost::any JacobianAction (unsigned int const wrtIn, unsigned int const wrtOut, boost::any const &vec, Args... args)
Evaluate the action of the Jacobian of this muq::Modeling::WorkPiece using multiple arguments.
void JacobianActionByFD (unsigned int const wrtIn, unsigned int const wrtOut, boost::any const &vec, ref_vector< boost::any > const &input)
Compute the action of the Jacobian using finite differences.
boost::any JacobianTransposeAction (unsigned int const wrtIn, unsigned int const wrtOut, boost::any const &vec, std::vector< boost::any > const &ins)
Evaluate the action of the Jacobian transpose of this muq::Modeling::WorkPiece using references to the inputs.
boost::any JacobianTransposeAction (unsigned int const wrtIn, unsigned int const wrtOut, boost::any const &vec, ref_vector< boost::any > const &ins)
Evaluate the action of the Jacobian transpose of this muq::Modeling::WorkPiece using references to the inputs.
template<typename... Args>
boost::any JacobianTransposeAction (unsigned int const wrtIn, unsigned int const wrtOut, boost::any const &vec, Args... args)
Evaluate the action of the Jacobian transpose of this muq::Modeling::WorkPiece using multiple arguments.
void JacobianTransposeActionByFD (unsigned int const wrtIn, unsigned int const wrtOut, boost::any const &vec, ref_vector< boost::any > const &inputs)
Compute the action of the Jacobian transpose using finite differences.
std::string Name () const
Get the (unique) name of this work piece.
std::string InputType (unsigned int inputNum, bool const demangle=true) const
Get the input type (if we know it) for a specific input.
std::string OutputType (unsigned int outputNum, bool const demangle=true) const
Get the output type (if we know it) for a specific output.
std::map< unsigned int, std::string > OutputTypes () const
Get the output types.
std::map< unsigned int, std::string > InputTypes () const
Get the input types.
unsigned int ID () const
Get the unique ID number.
Public Attributes
int numInputs
The number of inputs.
int numOutputs
The number of outputs.
Friends
class WorkGraphPiece
class WorkGraph
Member Enumeration Documentation
Fix
enum muq::Modeling::WorkPiece::Fix protected
Does the constructor fix the inputs or the outputs?
Enumerator
Inputs
The constructor fixes the input number and possibly the types.
Outputs
The constructor fixes the output number and possibly the types.
Definition at line 36 of file WorkPiece.h.
Constructor & Destructor Documentation
WorkPiece() [1/19]
WorkPiece::WorkPiece ()
Create a muq::Modeling::WorkPiece with no fixed number of inputs and outputs and variable input/output types.
Definition at line 9 of file WorkPiece.cpp.
WorkPiece() [2/19]
WorkPiece::WorkPiece (int const num, WorkPiece::Fix const fix = WorkPiece::Fix::Inputs)
Create a muq::Modeling::WorkPiece with either a fixed number of inputs or outputs and variable input/output types.
Parameters
[in] num The number of inputs or outputs (which one depends on the second parameter)
[in] fix WorkPiece::Fix::Inputs (default): the first parameter is the number of inputs; WorkPiece::Fix::Outputs: the first parameter is the number of outputs
Definition at line 16 of file WorkPiece.cpp.
WorkPiece() [3/19]
WorkPiece::WorkPiece (int const numIns, int const numOuts)
Create a muq::Modeling::WorkPiece with a fixed number of inputs and outputs but variable input/output types.
Parameters
[in] numIns The number of inputs
[in] numOuts The number of outputs
Definition at line 23 of file WorkPiece.cpp.
WorkPiece() [4/19]
WorkPiece::WorkPiece (std::vector< std::string > const & types, WorkPiece::Fix const fix = WorkPiece::Fix::Inputs)
Create a muq::Modeling::WorkPiece with either a fixed number of inputs with specified types or a fixed number of outputs with specified types.
If the number and type of the inputs is specified then the number and type of the outputs is variable. The opposite is true if the number and type of the outputs is specified.
Parameters
[in] types A vector of strings, each element is the type of an input or output (the number of inputs or outputs is the size of this vector)
[in] fix WorkPiece::Fix::Inputs (default): the elements of the first parameter are the types of the inputs; WorkPiece::Fix::Outputs: the elements of the first parameter are the types of the outputs
Definition at line 30 of file WorkPiece.cpp.
WorkPiece() [5/19]
WorkPiece::WorkPiece (std::map< unsigned int, std::string > const & types, WorkPiece::Fix const fix = WorkPiece::Fix::Inputs)
Create a muq::Modeling::WorkPiece where either some of the inputs have specified types or some of the outputs have specified types.
If the inputs are specified, then the outputs are not (and vice versa). The number of in/outputs is variable but some of them have specified type. For example, if the first input is a string and the third input is a double then
Evaluate("string", 1.0, 2.0);
Evaluate("string");
Evaluate();
Evaluate("string", "another string", 5.0, std::shared_ptr<AnObject>);
are valid muq::Modeling::WorkPiece::Evaluate calls but
Evaluate(1.0, 2.0, "string");
is not valid.
Parameters
[in] types A map from the input/output number to the input/output type
[in] fix WorkPiece::Fix::Inputs (default): the elements of the first parameter are the types of the inputs; WorkPiece::Fix::Outputs: the elements of the first parameter are the types of the outputs
Definition at line 39 of file WorkPiece.cpp.
WorkPiece() [6/19]
WorkPiece::WorkPiece (std::map< unsigned int, std::string > const & types, int const num, WorkPiece::Fix const fixTypes = WorkPiece::Fix::Inputs, WorkPiece::Fix const fixNum = WorkPiece::Fix::Inputs)
Create a muq::Modeling::WorkPiece where either some of the inputs have specified types or some of the outputs have specified types and either the number of inputs or the number of outputs is fixed.
Parameters
[in] types A map from the input/output number to the input/output type
[in] num The number of inputs/outputs
[in] fixTypes WorkPiece::Fix::Inputs (default): the elements of the first parameter are the types of the inputs; WorkPiece::Fix::Outputs: the elements of the first parameter are the types of the outputs
[in] fixNum WorkPiece::Fix::Inputs (default): the second parameter is the number of inputs; WorkPiece::Fix::Outputs: the second parameter is the number of outputs
Definition at line 48 of file WorkPiece.cpp.
WorkPiece() [7/19]
WorkPiece::WorkPiece (std::vector< std::string > const & types, int const num)
Create a muq::Modeling::WorkPiece with a fixed number of inputs with specified types and a fixed number of outputs (of uknown type)
Parameters
[in] types A vector of strings, each element is the type of an input (the number of inputs is the size of this vector)
[in] num The number of outputs
Definition at line 57 of file WorkPiece.cpp.
WorkPiece() [8/19]
WorkPiece::WorkPiece (int const num, std::vector< std::string > const & types)
Create a muq::Modeling::WorkPiece with a fixed number of outputs with specified types and a fixed number of inputs (of uknown type)
Parameters
[in] num The number of inputs
[in] types A vector of strings, each element is the type of an output (the number of outputs is the size of this vector)
Definition at line 65 of file WorkPiece.cpp.
WorkPiece() [9/19]
WorkPiece::WorkPiece (std::map< unsigned int, std::string > const & inTypes, int const numIns, int const numOuts)
Create a muq::Modeling::WorkPiece where some of the inputs are known and we know the input and output numbers.
Parameters
[in] inTypes A map from the input number to the input type
[in] numIns The number of inputs
[in] numOuts The number of outputs
Definition at line 73 of file WorkPiece.cpp.
WorkPiece() [10/19]
WorkPiece::WorkPiece (int const numIns, std::map< unsigned int, std::string > const & outTypes, int const numOuts)
Create a muq::Modeling::WorkPiece where some of the outputs are known and we know the input and output numbers.
Parameters
[in] numIns The number of inputs
[in] outTypes A map from the input number to the input type
[in] numOuts The number of outputs
Definition at line 81 of file WorkPiece.cpp.
WorkPiece() [11/19]
WorkPiece::WorkPiece (std::vector< std::string > const & inTypes, std::vector< std::string > const & outTypes)
Create a muq::Modeling::WorkPiece with a fixed number of inputs and outputs with specified types.
Parameters
[in] inTypes A vector of strings, each element is the type of an input (the number of inputs is the size of this vector)
[in] outTypes A vector of strings, each element is the type of an output (the number of outputs is the size of this vector)
Definition at line 89 of file WorkPiece.cpp.
WorkPiece() [12/19]
WorkPiece::WorkPiece (std::map< unsigned int, std::string > const & inTypes, std::vector< std::string > const & outTypes)
Create a muq::Modeling::WorkPiece where some of the inputs are known and all of the outputs have specified types.
Parameters
[in] inTypes A map from the input number to the input type
[in] outTypes A vector of strings, each element is the type of an output (the number of outputs is the size of this vector)
Definition at line 98 of file WorkPiece.cpp.
WorkPiece() [13/19]
WorkPiece::WorkPiece (std::map< unsigned int, std::string > const & inTypes, int const num, std::vector< std::string > const & outTypes)
Create a muq::Modeling::WorkPiece where some of the inputs are known with a known number of inputs and all of the outputs have specified types.
Parameters
[in] inTypes A map from the input number to the input type
[in] num The number of inputs
[in] outTypes A vector of strings, each element is the type of an output (the number of outputs is the size of this vector)
Definition at line 107 of file WorkPiece.cpp.
WorkPiece() [14/19]
WorkPiece::WorkPiece (std::vector< std::string > const & inTypes, std::map< unsigned int, std::string > const & outTypes)
Create a muq::Modeling::WorkPiece where some of the outputs and all of the inputs have specified types.
Parameters
[in] inTypes A vector of strings, each element is the type of an input (the number of inputs is the size of this vector)
[in] outTypes A map from the output number to the output type
Definition at line 116 of file WorkPiece.cpp.
WorkPiece() [15/19]
WorkPiece::WorkPiece (std::vector< std::string > const & inTypes, std::map< unsigned int, std::string > const & outTypes, int const num)
Create a muq::Modeling::WorkPiece where some of the outputs with a known number of outputs and all of the inputs have specified types.
Parameters
[in] inTypes A vector of strings, each element is the type of an input (the number of inputs is the size of this vector)
[in] outTypes A map from the output number to the output type
[in] num The number of outputs
Definition at line 125 of file WorkPiece.cpp.
WorkPiece() [16/19]
WorkPiece::WorkPiece (std::map< unsigned int, std::string > const & inTypes, std::map< unsigned int, std::string > const & outTypes)
Create a muq::Mdoeling::WorkPiece where some of the inputs and some of the outputs have specified types.
Parameters
[in] inTypes A map from the input number to the input type
[in] outTypes A map from the output number to the output type
Definition at line 134 of file WorkPiece.cpp.
WorkPiece() [17/19]
WorkPiece::WorkPiece (std::map< unsigned int, std::string > const & inTypes, int const numIn, std::map< unsigned int, std::string > const & outTypes)
Create a muq::Mdoeling::WorkPiece where some of the inputs and some of the outputs have specified types with a fixed number of inputs.
Parameters
[in] inTypes A map from the input number to the input type
[in] numIn The number of inputs
[in] outTypes A map from the output number to the output type
Definition at line 143 of file WorkPiece.cpp.
WorkPiece() [18/19]
WorkPiece::WorkPiece (std::map< unsigned int, std::string > const & inTypes, std::map< unsigned int, std::string > const & outTypes, int const numOut)
Create a muq::Mdoeling::WorkPiece where some of the inputs and some of the outputs have specified types with a fixed number of outputs.
Parameters
[in] inTypes A map from the input number to the input type
[in] outTypes A map from the output number to the output type
[in] outNum The number of outputs
Definition at line 152 of file WorkPiece.cpp.
WorkPiece() [19/19]
WorkPiece::WorkPiece (std::map< unsigned int, std::string > const & inTypes, int const numIn, std::map< unsigned int, std::string > const & outTypes, int const numOut)
Create a muq::Mdoeling::WorkPiece where some of the inputs and some of the outputs have specified types with a fixed number of inputs and outputs.
Parameters
[in] inTypes A map from the input number to the input type
[in] numIn The number of inputs
[in] outTypes A map from the output number to the output type
[in] outNum The number of outputs
Definition at line 161 of file WorkPiece.cpp.
~WorkPiece()
virtual muq::Modeling::WorkPiece::~WorkPiece () inline virtual
Default destructor.
Definition at line 197 of file WorkPiece.h.
References Evaluate().
Member Function Documentation
CheckInputType()
bool WorkPiece::CheckInputType (unsigned int const inputNum, std::string const & type) const private
Check the input type.
Parameters
[in] inputNum The input number — we are check that the type has the same type as this input
[in] type The type of the input
Returns
true: The input matches the specified type or no input type is specified, false: the input type does not match the specified type
Definition at line 618 of file WorkPiece.cpp.
References inputTypes.
Referenced by Evaluate(), EvaluateRecursive(), Jacobian(), JacobianAction(), JacobianActionRecursive(), JacobianRecursive(), JacobianTransposeAction(), and JacobianTransposeActionRecursive().
CheckOutputType()
bool WorkPiece::CheckOutputType (unsigned int const outputNum, std::string const & type) const private
Check the output type.
Parameters
[in] outputNum The output number — we are check that the computed type has the same type as this output
[in] type The type of the output
Returns
true: The output matches the specified type or no output type is specified, false: the output type does not match the specified type
Definition at line 631 of file WorkPiece.cpp.
References outputTypes.
Referenced by Evaluate(), and JacobianTransposeActionRecursive().
Clear()
void WorkPiece::Clear () private
Clear muq::Modeling::WorkPiece::outputs when muq::Modeling::Evaluate is called.
Definition at line 591 of file WorkPiece.cpp.
References clearOutputs, and outputs.
Referenced by Evaluate(), and JacobianTransposeActionRecursive().
ClearDerivatives()
void WorkPiece::ClearDerivatives () private
Clear muq::Modeling::WorkPiece::outputs and muq::Modeling::WorkPiece::jacobian, muq::Modeling::WorkPiece::jacobianAction, and muq::Modeling::WorkPiece::jacobianTransposeAction when muq::Modeling::Jacobian, muq::Modeling::JacobianAction, or muq::Modeling::JacobianTransposeAction() is called.
Definition at line 604 of file WorkPiece.cpp.
References clearDerivatives, jacobian, jacobianAction, and jacobianTransposeAction.
Referenced by Jacobian(), JacobianAction(), JacobianTransposeAction(), and JacobianTransposeActionRecursive().
Evaluate() [1/4]
std::vector< boost::any > WorkPiece::Evaluate (std::vector< boost::any > const & ins)
Evaluate this muq::Modeling::WorkPiece.
This function takes the inputs to the muq::Modeling::WorkPiece, which must match WorkPiece::numInputs and WorkPiece::inputTypes if they are specified. It then calls WorkPiece::EvaluateImpl(), which populates WorkPiece::outputs using the input arguments (passed to WorkPiece::EvaluateImpl()). This function then checks WorkPiece::outputs, which much match WorkPiece::numOutputs and WorkPiece::outputTypes if they are specified.
This function builds a reference vector to the inputs and calls WorkPiece::Evaluate(ref_vector<boost::any> const& ins)
Parameters
[in] ins A vector of inputs
Returns
The outputs of this muq::Modeling::WorkPiece
Definition at line 246 of file WorkPiece.cpp.
References CheckInputType(), Evaluate(), inputTypes, numInputs, and ToRefVector().
Evaluate() [2/4]
std::vector< boost::any > WorkPiece::Evaluate (ref_vector< boost::any > const & ins)
Evaluate this muq::Modeling::WorkPiece using references to the inputs.
This function takes the references to the inputs to the muq::Modeling::WorkPiece, which must match WorkPiece::numInputs and WorkPiece::inputTypes if they are specified. It then calls WorkPiece::EvaluateImpl(), which populates WorkPiece::outputs using the input arguments (passed to WorkPiece::EvaluateImpl()). This function then checks WorkPiece::outputs, which much match WorkPiece::numOutputs and WorkPiece::outputTypes if they are specified.
References are used for efficiency in the muq::Modeling::WorkGraph.
Parameters
[in] ins A vector of references to the inputs
Returns
The outputs of this muq::Modeling::WorkPiece
Definition at line 225 of file WorkPiece.cpp.
References CheckOutputType(), Clear(), EvaluateImpl(), numInputs, numOutputs, and outputs.
Evaluate() [3/4]
std::vector< boost::any > WorkPiece::Evaluate ()
Evaluate this muq::Modeling::WorkPiece in the case that there are no inputs.
Returns
The outputs of this muq::Modeling::WorkPiece
Definition at line 202 of file WorkPiece.cpp.
References Clear(), EvaluateImpl(), numInputs, numOutputs, outputs, and outputTypes.
Referenced by Evaluate(), EvaluateRecursive(), JacobianByFD(), and ~WorkPiece().
Evaluate() [4/4]
template<typename... Args> std::vector<boost::any> muq::Modeling::WorkPiece::Evaluate (Args... args) inline
Evalaute this muq::Modeling::WorkPiece using multiple arguments.
This function allows the user to call WorkPiece::Evaluate without first creating a vector of inputs. Instead, the user calls WorkPiece::Evaluate with multiple arguments (if specified, the number of arguments must match the number of inputs) and this function creates the input vector.
Parameters
[in] args The inputs (may be more than one)
Returns
The outputs of this muq::Modeling::WorkPiece
Definition at line 232 of file WorkPiece.h.
References Clear(), EvaluateRecursive(), Jacobian(), and numInputs.
EvaluateImpl()
virtual void muq::Modeling::WorkPiece::EvaluateImpl (ref_vector< boost::any > const & inputs) private pure virtual
User-implemented function that determines the behavior of this muq::Modeling::WorkPiece.
This function determines how the WorkPiece::inputs determine WorkPiece::outputs. Must be implemented by a child.
WorkPiece::Evaluate() calls this function after checking the inputs and storing them in WorkPiece::inputs. This function populates WorkPiece::outputs, the outputs of this muq::Modeling::WorkPiece. WorkPiece::Evaluate() checks the outputs after calling this function.
Implemented in muq::Modeling::WorkGraphPiece, muq::Modeling::RootfindingIVP, and muq::Modeling::IdentityPiece.
Referenced by muq::Modeling::ConstantPiece::ConstantPiece(), Evaluate(), and muq::Modeling::ConstantPiece::SetOutputs().
EvaluateRecursive() [1/2]
template<typename ith , typename... Args> std::vector<boost::any> muq::Modeling::WorkPiece::EvaluateRecursive (ref_vector< boost::any > & inputs, ith const & in, Args... args) inline private
Creates WorkPiece::inputs when the WorkPiece::Evaluate is called with multiple arguments.
Parameters
[in] inputs The growing vector of inputs
[in] in The input corresponding to the \(i^{th}\) input
[in] args The remaining (greater than \(i\)) inputs
Returns
The outputs of this muq::Modeling::WorkPiece
Definition at line 543 of file WorkPiece.h.
References CheckInputType().
Referenced by Evaluate().
EvaluateRecursive() [2/2]
template<typename last > std::vector<boost::any> muq::Modeling::WorkPiece::EvaluateRecursive (ref_vector< boost::any > & inputs, last const & in) inline private
Creates WorkPiece::inputs when the WorkPiece::Evaluate is called with multiple arguments.
Parameters
[in] inputs The growing vector of inputs
[in] in The input corresponding to the last input
Returns
The outputs of this muq::Modeling::WorkPiece
Definition at line 568 of file WorkPiece.h.
References CheckInputType(), Evaluate(), and JacobianImpl().
ID()
unsigned int WorkPiece::ID () const
Get the unique ID number.
Returns
The ID number
Definition at line 567 of file WorkPiece.cpp.
References id.
Referenced by JacobianTransposeAction().
InputType()
std::string WorkPiece::InputType (unsigned int inputNum, bool const demangle = true) const
Get the input type (if we know it) for a specific input.
The return input type name is "demangled" so it is more human readable.
Parameters
[in] inputNum The input we want the name of
[in] demangle true (default): demangle the input so it is human-readable, false: do not demangle the input
Returns
If we know the input types, the input type name is returned. If we do not know the input types, return ""
Definition at line 525 of file WorkPiece.cpp.
References inputTypes, and numInputs.
Referenced by JacobianActionImpl(), JacobianImpl(), JacobianTransposeAction(), and JacobianTransposeActionImpl().
InputTypes()
std::map< unsigned int, std::string > WorkPiece::InputTypes () const
Get the input types.
Definition at line 575 of file WorkPiece.cpp.
References inputTypes.
Referenced by JacobianTransposeAction().
Jacobian() [1/3]
boost::any WorkPiece::Jacobian (unsigned int const wrtIn, unsigned int const wrtOut, std::vector< boost::any > const & ins)
Evaluate the Jacobian of this muq::Modeling::WorkPiece using references to the inputs.
This function takes a vector of inputs to the muq::Modeling::WorkPiece, which must match WorkPiece::numInputs and WorkPiece::inputTypes if they are specified. It then calls WorkPiece::JacobianImpl(), which computes the Jacobian. The Jacobian must be implemented by a child class, unless both the input and the output are Eigen::VectorXd's. In this case, we default to finite difference.
Parameters
[in] wrtIn The input number we are taking the Jacobian with respect to
[in] wrtOut The output number we are taking the Jacobian with respect to
[in] ins A vector of inputs
Returns
The Jacobian of this muq::Modeling::WorkPiece
Definition at line 259 of file WorkPiece.cpp.
References CheckInputType(), inputTypes, numInputs, numOutputs, and ToRefVector().
Referenced by Evaluate(), JacobianActionByFD(), JacobianRecursive(), and JacobianTransposeActionByFD().
Jacobian() [2/3]
boost::any WorkPiece::Jacobian (unsigned int const wrtIn, unsigned int const wrtOut, ref_vector< boost::any > const & ins)
Evaluate the Jacobian of this muq::Modeling::WorkPiece using references to the inputs.
This function takes the references to the inputs to the muq::Modeling::WorkPiece, which must match WorkPiece::numInputs and WorkPiece::inputTypes if they are specified. It then calls WorkPiece::JacobianImpl(), which computes the Jacobian. The Jacobian must be implemented by a child class, unless both the input and the output are Eigen::VectorXd's. In this case, we default to finite difference.
References are used for efficiency in the muq::Modeling::WorkGraph.
Parameters
[in] wrtIn The input number we are taking the Jacobian with respect to
[in] wrtOut The output number we are taking the Jacobian with respect to
[in] ins A vector of references to the inputs
Returns
The Jacobian of this muq::Modeling::WorkPiece
Definition at line 276 of file WorkPiece.cpp.
References ClearDerivatives(), jacobian, JacobianImpl(), numInputs, and numOutputs.
Jacobian() [3/3]
template<typename... Args> boost::any muq::Modeling::WorkPiece::Jacobian (unsigned int const wrtIn, unsigned int const wrtOut, Args... args) inline
Evaluate the Jacobian of this muq::Modeling::WorkPiece using multiple arguments.
This function allows the user to compute the Jacobian of an output with respect to one of the inputs. If both the input and the output type is an Eigen::VectorXd and the user has not implemented the Jacobian, we default to finite difference.
Parameters
[in] wrtIn The input number we are taking the Jacobian with respect to
[in] wrtOut The output number we are taking the Jacobian with respect to
[in] args The inputs (may be more than one)
Returns
The Jacobian of this muq::Modeling::WorkPiece
Definition at line 275 of file WorkPiece.h.
References ClearDerivatives(), JacobianByFD(), JacobianRecursive(), numInputs, and numOutputs.
JacobianAction() [1/3]
boost::any WorkPiece::JacobianAction (unsigned int const wrtIn, unsigned int const wrtOut, boost::any const & vec, std::vector< boost::any > const & ins)
Evaluate the action of the Jacobian of this muq::Modeling::WorkPiece using references to the inputs.
This function takes a vector of inputs to the muq::Modeling::WorkPiece, which must match WorkPiece::numInputs and WorkPiece::inputTypes if they are specified. It then calls WorkPiece::JacobianActionImpl(), which computes the action of the Jacobian. The Jacobian must be implemented by a child class, unless the input and the output and the vector the Jacobian is action on are Eigen::VectorXd's. In this case, we call WorkPiece::Jacobian() and apply it to the vector.
Parameters
[in] wrtIn The input number we are taking the Jacobian with respect to
[in] wrtOut The output number we are taking the Jacobian with respect to
[in] vec We want to apply the Jacobian to this vector
[in] ins A vector of inputs
Returns
The Jacobian of this muq::Modeling::WorkPiece
Definition at line 367 of file WorkPiece.cpp.
References CheckInputType(), ClearDerivatives(), inputTypes, numInputs, numOutputs, and ToRefVector().
Referenced by JacobianActionRecursive().
JacobianAction() [2/3]
boost::any WorkPiece::JacobianAction (unsigned int const wrtIn, unsigned int const wrtOut, boost::any const & vec, ref_vector< boost::any > const & ins)
Evaluate the action of the Jacobian of this muq::Modeling::WorkPiece using references to the inputs.
References are used for efficiency in the muq::Modeling::WorkGraph.
Parameters
[in] wrtIn The input number we are taking the Jacobian with respect to
[in] wrtOut The output number we are taking the Jacobian with respect to
[in] vec We want to apply the Jacobian to this vector
[in] ins A vector of references to the inputs
Returns
The Jacobian of this muq::Modeling::WorkPiece
Definition at line 387 of file WorkPiece.cpp.
References jacobianAction, JacobianActionImpl(), numInputs, and numOutputs.
JacobianAction() [3/3]
template<typename... Args> boost::any muq::Modeling::WorkPiece::JacobianAction (unsigned int const wrtIn, unsigned int const wrtOut, boost::any const & vec, Args... args) inline
Evaluate the action of the Jacobian of this muq::Modeling::WorkPiece using multiple arguments.
This function allows the user to compute the action of the Jacobian of an output with respect to one of the inputs. If the vector given to this function, the input type and the output type is an Eigen::VectorXd and the user has not implemented the Jacobian action, we call muq::Modeling::Jacobian and apply it to the given vector
Parameters
[in] wrtIn The input number we are taking the Jacobian with respect to
[in] wrtOut The output number we are taking the Jacobian with respect to
[in] vec We want to apply the Jacobian to this vector
[in] args The inputs (may be more than one)
Returns
The action of the Jacobian of this muq::Modeling::WorkPiece on vec
Definition at line 334 of file WorkPiece.h.
References ClearDerivatives(), JacobianActionByFD(), JacobianActionRecursive(), JacobianTransposeAction(), numInputs, and numOutputs.
JacobianActionByFD()
void WorkPiece::JacobianActionByFD (unsigned int const wrtIn, unsigned int const wrtOut, boost::any const & vec, ref_vector< boost::any > const & input)
Compute the action of the Jacobian using finite differences.
Assume the input and output type are Eigen::VectorXd.
Parameters
[in] wrtIn The input number we are taking the Jacobian with respect to
[in] wrtOut The output number we are taking the Jacobian with respect to
[in] vec We want to apply the Jacobian to this vector
[in] args The inputs (may be more than one)
Definition at line 425 of file WorkPiece.cpp.
References Jacobian(), jacobian, and jacobianAction.
Referenced by JacobianAction(), and JacobianActionImpl().
JacobianActionImpl()
void WorkPiece::JacobianActionImpl (unsigned int const wrtIn, unsigned int const wrtOut, boost::any const & vec, ref_vector< boost::any > const & inputs) private virtual
User-implemented function that to compute the action of the Jacobian.
Parameters
[in] wrtIn The input number we are taking the Jacobian with respect to
[in] wrtOut The output number we are taking the Jacobian with respect to
[in] vec We want to apply the Jacobian to this vector
[in] inputs The vector of references to the inputs
Reimplemented in muq::Modeling::WorkGraphPiece.
Definition at line 408 of file WorkPiece.cpp.
References InputType(), JacobianActionByFD(), and OutputType().
Referenced by JacobianAction(), muq::Modeling::ODE::JacobianImpl(), and JacobianRecursive().
JacobianActionRecursive() [1/2]
template<typename ith , typename... Args> boost::any muq::Modeling::WorkPiece::JacobianActionRecursive (unsigned int const wrtIn, unsigned int const wrtOut, boost::any const & vec, ref_vector< boost::any > & inputs, ith const & in, Args... args) inline private
Creates WorkPiece::inputs when the WorkPiece::JacobianAction is called with multiple arguments.
Parameters
[in] wrtIn The input number we are taking the Jacobian with respect to
[in] wrtOut The output number we are taking the Jacobian with respect to
[in] vec We want to apply the Jacobian to this vector
[in] inputs The growing vector of inputs
[in] in The input corresponding to the \(i^{th}\) input
[in] args The remaining (greater than \(i\)) inputs
Returns
The action of the Jacobian of this muq::Modeling::WorkPiece on vec
Definition at line 666 of file WorkPiece.h.
References CheckInputType().
Referenced by JacobianAction().
JacobianActionRecursive() [2/2]
template<typename last > boost::any muq::Modeling::WorkPiece::JacobianActionRecursive (unsigned int const wrtIn, unsigned int const wrtOut, boost::any const & vec, ref_vector< boost::any > & inputs, last const & in) inline private
Creates WorkPiece::inputs when the WorkPiece::JacobianAction is called with multiple arguments.
Parameters
[in] wrtIn The input number we are taking the Jacobian with respect to
[in] wrtOut The output number we are taking the Jacobian with respect to
[in] vec We want to apply the Jacobian to this vector
[in] inputs The growing vector of inputs
[in] in The input corresponding to the last input
Returns
The action of the Jacobian of this muq::Modeling::WorkPiece on vec
Definition at line 693 of file WorkPiece.h.
References CheckInputType(), JacobianAction(), and JacobianTransposeActionImpl().
JacobianByFD()
void WorkPiece::JacobianByFD (unsigned int const wrtIn, unsigned int const wrtOut, ref_vector< boost::any > const & inputs, double const relTol = 1.0e-4, const double minTol = 1.0e-6)
Compute the Jacobian using finite differences.
Assume the input and output type are Eigen::VectorXd.
Parameters
[in] wrtIn The input number we are taking the Jacobian with respect to
[in] wrtOut The output number we are taking the Jacobian with respect to
[in] args The inputs (may be more than one)
[in] refTol Scaled value for the finite difference step size (defaults to 1e-4)
[in] minTol Minimum value for the finite difference step size (defaults to 1e-6)
Definition at line 324 of file WorkPiece.cpp.
References Evaluate(), and jacobian.
Referenced by Jacobian(), and JacobianImpl().
JacobianImpl()
void WorkPiece::JacobianImpl (unsigned int const wrtIn, unsigned int const wrtOut, ref_vector< boost::any > const & inputs) private virtual
User-implemented function that to compute the Jacobian.
If th user does not implement this function, the Jacobian cannot be computed. However, if both the input and the output type are Eigen::VectorXd, we default to finite difference.
Parameters
[in] wrtIn The input number we are taking the Jacobian with respect to
[in] wrtOut The output number we are taking the Jacobian with respect to
[in] inputs The vector of references to the inputs
Reimplemented in muq::Modeling::WorkGraphPiece, muq::Modeling::RootfindingIVP, and muq::Modeling::ODE.
Definition at line 305 of file WorkPiece.cpp.
References InputType(), jacobian, JacobianByFD(), and OutputType().
Referenced by EvaluateRecursive(), and Jacobian().
JacobianRecursive() [1/2]
template<typename ith , typename... Args> boost::any muq::Modeling::WorkPiece::JacobianRecursive (unsigned int const wrtIn, unsigned int const wrtOut, ref_vector< boost::any > & inputs, ith const & in, Args... args) inline private
Creates WorkPiece::inputs when the WorkPiece::Jacobian is called with multiple arguments.
Parameters
[in] wrtIn The input number we are taking the Jacobian with respect to
[in] wrtOut The output number we are taking the Jacobian with respect to
[in] inputs The growing vector of inputs
[in] in The input corresponding to the \(i^{th}\) input
[in] args The remaining (greater than \(i\)) inputs
Returns
The Jacobian of this muq::Modeling::WorkPiece
Definition at line 604 of file WorkPiece.h.
References CheckInputType().
Referenced by Jacobian().
JacobianRecursive() [2/2]
template<typename last > boost::any muq::Modeling::WorkPiece::JacobianRecursive (unsigned int const wrtIn, unsigned int const wrtOut, ref_vector< boost::any > & inputs, last const & in) inline private
Creates WorkPiece::inputs when the WorkPiece::Jacobian is called with multiple arguments.
Parameters
[in] wrtIn The input number we are taking the Jacobian with respect to
[in] wrtOut The output number we are taking the Jacobian with respect to
[in] inputs The growing vector of inputs
[in] in The input corresponding to the last input
Returns
The Jacobian of this muq::Modeling::WorkPiece
Definition at line 630 of file WorkPiece.h.
References CheckInputType(), Jacobian(), and JacobianActionImpl().
JacobianTransposeAction() [1/3]
boost::any WorkPiece::JacobianTransposeAction (unsigned int const wrtIn, unsigned int const wrtOut, boost::any const & vec, std::vector< boost::any > const & ins)
Evaluate the action of the Jacobian transpose of this muq::Modeling::WorkPiece using references to the inputs.
This function takes a vector of inputs to the muq::Modeling::WorkPiece, which must match WorkPiece::numInputs and WorkPiece::inputTypes if they are specified. It then calls WorkPiece::JacobianTransposeActionImpl(), which computes the action of the Jacobian transpose. The Jacobian must be implemented by a child class, unless the input and the output and the vector the Jacobian transpose is action on are Eigen::VectorXd's. In this case, we call WorkPiece::Jacobian() and apply it to the vector.
Parameters
[in] wrtIn The input number we are taking the Jacobian with respect to
[in] wrtOut The output number we are taking the Jacobian with respect to
[in] vec We want to apply the Jacobian to this vector
[in] ins A vector of inputs
Returns
The Jacobian of this muq::Modeling::WorkPiece
Definition at line 441 of file WorkPiece.cpp.
References CheckInputType(), ClearDerivatives(), inputTypes, numInputs, numOutputs, and ToRefVector().
Referenced by JacobianAction(), and JacobianTransposeActionRecursive().
JacobianTransposeAction() [2/3]
boost::any WorkPiece::JacobianTransposeAction (unsigned int const wrtIn, unsigned int const wrtOut, boost::any const & vec, ref_vector< boost::any > const & ins)
Evaluate the action of the Jacobian transpose of this muq::Modeling::WorkPiece using references to the inputs.
References are used for efficiency in the muq::Modeling::WorkGraph.
Parameters
[in] wrtIn The input number we are taking the Jacobian with respect to
[in] wrtOut The output number we are taking the Jacobian with respect to
[in] vec We want to apply the Jacobian to this vector
[in] ins A vector of references to the inputs
Returns
The Jacobian of this muq::Modeling::WorkPiece
Definition at line 461 of file WorkPiece.cpp.
References jacobianTransposeAction, JacobianTransposeActionImpl(), numInputs, and numOutputs.
JacobianTransposeAction() [3/3]
template<typename... Args> boost::any muq::Modeling::WorkPiece::JacobianTransposeAction (unsigned int const wrtIn, unsigned int const wrtOut, boost::any const & vec, Args... args) inline
Evaluate the action of the Jacobian transpose of this muq::Modeling::WorkPiece using multiple arguments.
This function allows the user to compute the action of the Jacobian transpose of an output with respect to one of the inputs. If the vector given to this function, the input type and the output type is an Eigen::VectorXd and the user has not implemented the Jacobian transpose action, we call muq::Modeling::Jacobian and apply it to the given vector
Parameters
[in] wrtIn The input number we are taking the Jacobian with respect to
[in] wrtOut The output number we are taking the Jacobian with respect to
[in] vec We want to apply the Jacobian transpose to this vector
[in] args The inputs (may be more than one)
Returns
The action of the Jacobian transpose of this muq::Modeling::WorkPiece on vec
Definition at line 392 of file WorkPiece.h.
References ClearDerivatives(), ID(), InputType(), InputTypes(), JacobianTransposeActionByFD(), JacobianTransposeActionRecursive(), Name(), numInputs, numOutputs, OutputType(), and OutputTypes().
JacobianTransposeActionByFD()
void WorkPiece::JacobianTransposeActionByFD (unsigned int const wrtIn, unsigned int const wrtOut, boost::any const & vec, ref_vector< boost::any > const & inputs)
Compute the action of the Jacobian transpose using finite differences.
Assume the input and output type are Eigen::VectorXd.
Parameters
[in] wrtIn The input number we are taking the Jacobian with respect to
[in] wrtOut The output number we are taking the Jacobian with respect to
[in] vec We want to apply the Jacobian transpose to this vector
[in] args The inputs (may be more than one)
Definition at line 499 of file WorkPiece.cpp.
References Jacobian(), jacobian, and jacobianTransposeAction.
Referenced by JacobianTransposeAction(), and JacobianTransposeActionImpl().
JacobianTransposeActionImpl()
void WorkPiece::JacobianTransposeActionImpl (unsigned int const wrtIn, unsigned int const wrtOut, boost::any const & vec, ref_vector< boost::any > const & inputs) private virtual
User-implemented function that to compute the action of the Jacobian transpose.
Parameters
[in] wrtIn The input number we are taking the Jacobian with respect to
[in] wrtOut The output number we are taking the Jacobian with respect to
[in] vec We want to apply the Jacobian transpose to this vector
[in] inputs The vector of references to the inputs
Reimplemented in muq::Modeling::WorkGraphPiece, and muq::Modeling::ODE.
Definition at line 482 of file WorkPiece.cpp.
References InputType(), JacobianTransposeActionByFD(), and OutputType().
Referenced by JacobianActionRecursive(), and JacobianTransposeAction().
JacobianTransposeActionRecursive() [1/2]
template<typename ith , typename... Args> boost::any muq::Modeling::WorkPiece::JacobianTransposeActionRecursive (unsigned int const wrtIn, unsigned int const wrtOut, boost::any const & vec, ref_vector< boost::any > & inputs, ith const & in, Args... args) inline private
Creates WorkPiece::inputs when the WorkPiece::JacobianTransposeAction is called with multiple arguments.
Parameters
[in] wrtIn The input number we are taking the Jacobian with respect to
[in] wrtOut The output number we are taking the Jacobian with respect to
[in] vec We want to apply the Jacobian transpose on this vector
[in] inputs The growing vector of inputs
[in] in The input corresponding to the \(i^{th}\) input
[in] args The remaining (greater than \(i\)) inputs
Returns
The action of the Jacobian of this muq::Modeling::WorkPiece on vec
Definition at line 729 of file WorkPiece.h.
References CheckInputType().
Referenced by JacobianTransposeAction().
JacobianTransposeActionRecursive() [2/2]
template<typename last > boost::any muq::Modeling::WorkPiece::JacobianTransposeActionRecursive (unsigned int const wrtIn, unsigned int const wrtOut, boost::any const & vec, ref_vector< boost::any > & inputs, last const & in) inline private
Creates WorkPiece::inputs when the WorkPiece::JacobianTransposeAction is called with multiple arguments.
Parameters
[in] wrtIn The input number we are taking the Jacobian with respect to
[in] wrtOut The output number we are taking the Jacobian with respect to
[in] vec We want to apply the Jacobian transpose to this vector
[in] inputs The growing vector of inputs
[in] in The input corresponding to the last input
Returns
The action of the Jacobian of this muq::Modeling::WorkPiece on vec
Definition at line 756 of file WorkPiece.h.
References CheckInputType(), CheckOutputType(), Clear(), ClearDerivatives(), JacobianTransposeAction(), and SetID().
Name()
std::string WorkPiece::Name () const
Get the (unique) name of this work piece.
Returns
The name of the muq::Modeling::WorkPiece
Definition at line 515 of file WorkPiece.cpp.
Referenced by JacobianTransposeAction().
OutputType()
std::string WorkPiece::OutputType (unsigned int outputNum, bool const demangle = true) const
Get the output type (if we know it) for a specific output.
The return output type name is "demangled" so it is more human readable.
Parameters
[in] outputNum The output we want the name of
[in] demangle true (default): demangle the input so it is human-readable, false: do not demangle the input
Returns
If we know the output types, the output type name is returned. If we do not know the output types, return ""
Definition at line 546 of file WorkPiece.cpp.
References numOutputs, and outputTypes.
Referenced by JacobianActionImpl(), JacobianImpl(), JacobianTransposeAction(), and JacobianTransposeActionImpl().
OutputTypes()
std::map< unsigned int, std::string > WorkPiece::OutputTypes () const
Get the output types.
Definition at line 571 of file WorkPiece.cpp.
References outputTypes.
Referenced by JacobianTransposeAction().
SetID()
unsigned int WorkPiece::SetID () private
Set the ID number, must be called by the constructor.
Definition at line 197 of file WorkPiece.cpp.
Referenced by JacobianTransposeActionRecursive().
ToRefVector()
ref_vector< const boost::any > WorkPiece::ToRefVector (std::vector< boost::any > const & anyVec) const protected
Create vector of references from a vector of boost::any's.
Definition at line 579 of file WorkPiece.cpp.
Referenced by Evaluate(), Jacobian(), JacobianAction(), JacobianTransposeAction(), and muq::Modeling::WorkGraphPiece::OutputMap().
Types() [1/2]
std::vector< std::string > WorkPiece::Types (std::vector< boost::any > const & vec) const protected
Get the types from a vector of boost::any's.
Parameters
[in] vec A vector of boost::any's
Returns
A vector of the types of the boost::any's
Definition at line 181 of file WorkPiece.cpp.
References types.
Referenced by muq::Modeling::ConstantPiece::ConstantPiece().
Types() [2/2]
std::map< unsigned int, std::string > WorkPiece::Types (std::vector< std::string > const & typesVec) const protected
Convert a vector of input types to a map.
The key in the map is the index of the vector.
Parameters
[in] typesVec A vector of input types
Returns
A map of input types
Definition at line 169 of file WorkPiece.cpp.
Friends And Related Function Documentation
WorkGraph
friend class WorkGraph friend
Definition at line 31 of file WorkPiece.h.
WorkGraphPiece
friend class WorkGraphPiece friend
Definition at line 30 of file WorkPiece.h.
Member Data Documentation
clearDerivatives
bool muq::Modeling::WorkPiece::clearDerivatives = true protected
Clear derivatives every time Jacobian, JacobianAction, or JacobianActionTranspose is called.
Definition at line 479 of file WorkPiece.h.
Referenced by ClearDerivatives().
clearOutputs
bool muq::Modeling::WorkPiece::clearOutputs = true protected
Clear outputs every time Evaluate is called.
If true, muq::Modeling::WorkPiece::outputs is cleared everytime muq::Modeling::WorkPiece::Evaluate is called. If false, the outputs are not cleared. Defaults to true.
Definition at line 476 of file WorkPiece.h.
Referenced by Clear(), and muq::Modeling::ConstantPiece::ConstantPiece().
id
const unsigned int muq::Modeling::WorkPiece::id private
A unique ID number assigned by the constructor.
Definition at line 798 of file WorkPiece.h.
Referenced by ID(), and muq::Modeling::WorkGraphPiece::RequiredOutputs().
inputTypes
std::map<unsigned int, std::string> muq::Modeling::WorkPiece::inputTypes protected
The input types.
Each element specifies the type of the corresponding input. This vector must have the same number of elements as WorkPiece::numInputs or it is empty (default), which indicates that the input types are variable.
Definition at line 509 of file WorkPiece.h.
Referenced by CheckInputType(), Evaluate(), InputType(), InputTypes(), Jacobian(), JacobianAction(), JacobianTransposeAction(), muq::Modeling::ODEBase::SetInputOutputTypes(), and muq::Modeling::RootfindingIVP::UpdateInputOutputTypes().
jacobian
boost::optional<boost::any> muq::Modeling::WorkPiece::jacobian protected
The Jacobian.
The Jacobian, which is filled by WorkPiece::JacobianImpl().
Definition at line 491 of file WorkPiece.h.
Referenced by ClearDerivatives(), muq::Modeling::ODEBase::ClearJacobian(), muq::Modeling::ODEBase::InitializeDerivative(), Jacobian(), JacobianActionByFD(), JacobianByFD(), muq::Modeling::RootfindingIVP::JacobianImpl(), muq::Modeling::WorkGraphPiece::JacobianImpl(), JacobianImpl(), JacobianTransposeActionByFD(), and muq::Modeling::ODE::SaveDerivative().
jacobianAction
boost::optional<boost::any> muq::Modeling::WorkPiece::jacobianAction protected
The action of the Jacobian.
The action of the Jacobian, which is filled by WorkPiece::JacobianActionImpl().
Definition at line 497 of file WorkPiece.h.
Referenced by ClearDerivatives(), muq::Modeling::ODEBase::ClearJacobianAction(), muq::Modeling::ODEBase::InitializeDerivative(), JacobianAction(), JacobianActionByFD(), muq::Modeling::WorkGraphPiece::JacobianActionImpl(), muq::Modeling::ODEBase::RHSJacobianAction(), and muq::Modeling::ODE::SaveDerivative().
jacobianTransposeAction
boost::optional<boost::any> muq::Modeling::WorkPiece::jacobianTransposeAction protected
The action of the Jacobian transpose.
The action of the Jacobian transpose, which is filled by WorkPiece::JacobianTransposeActionImpl().
Definition at line 503 of file WorkPiece.h.
Referenced by ClearDerivatives(), muq::Modeling::ODEBase::ClearJacobianTransposeAction(), muq::Modeling::ODEBase::InitializeDerivative(), JacobianTransposeAction(), JacobianTransposeActionByFD(), muq::Modeling::WorkGraphPiece::JacobianTransposeActionImpl(), and muq::Modeling::ODE::SaveDerivative().
numInputs
int muq::Modeling::WorkPiece::numInputs
The number of inputs.
Definition at line 455 of file WorkPiece.h.
Referenced by Evaluate(), muq::Modeling::RootfindingIVP::FindRoot(), muq::Modeling::ODE::ForwardSensitivity(), InputType(), muq::Modeling::ODE::Integrate(), Jacobian(), JacobianAction(), muq::Modeling::ODE::JacobianImpl(), JacobianTransposeAction(), and muq::Modeling::WorkGraphPiece::WorkGraphPiece().
numOutputs
int muq::Modeling::WorkPiece::numOutputs
The number of outputs.
Definition at line 458 of file WorkPiece.h.
Referenced by muq::Modeling::ConstantPiece::ConstantPiece(), Evaluate(), Jacobian(), JacobianAction(), JacobianTransposeAction(), and OutputType().
outputs
std::vector<boost::any> muq::Modeling::WorkPiece::outputs = std::vector<boost::any>(0) protected
The outputs.
The outputs of this muq::Modeling::WorkPiece are filled by WorkPiece::EvaluateImpl(). If the number of outputs is specified (i.e., WorkPiece::numOutputs is not -1) then WorkPiece::Evaluate() checks to make sure the size of this vector is equal to WorkPiece::numOutputs after calling WorkPiece::EvaluateImpl(). If the output types are specified (i.e., WorkPiece::outputTypes is not an empty vector) then WorkPiece::Evaluate() checks that the output types match WorkPiece::outputTypes after calling WorkPiece::EvaluateImpl().
Definition at line 485 of file WorkPiece.h.
Referenced by Clear(), muq::Modeling::ODEBase::ClearOutputs(), muq::Modeling::ConstantPiece::ConstantPiece(), Evaluate(), muq::Modeling::IdentityPiece::EvaluateImpl(), muq::Modeling::WorkGraphPiece::EvaluateImpl(), muq::Modeling::RootfindingIVP::JacobianImpl(), and muq::Modeling::ODEBase::TimeIndices().
outputTypes
std::map<unsigned int, std::string> muq::Modeling::WorkPiece::outputTypes protected
The output types.
Each element specifies the type of the corresponding output. This vector must have the same number of elements as WorkPiece::numOutputs or it is empty (default), which indicates that the output types are variable.
Definition at line 515 of file WorkPiece.h.
Referenced by CheckOutputType(), muq::Modeling::ConstantPiece::ConstantPiece(), Evaluate(), OutputType(), OutputTypes(), and muq::Modeling::RootfindingIVP::UpdateInputOutputTypes().
types
std::map<std::string, std::string> muq::Modeling::WorkPiece::types private
A map of common types.
A list of common types and their corresponding names:
"Eigen vector" for Eigen::VectorXd type
Definition at line 807 of file WorkPiece.h.
Referenced by Types().
The documentation for this class was generated from the following files:
/Users/andy/software/muq-private/MUQ/Modeling/WorkPiece.h
/Users/andy/software/muq-private/modules/Modeling/src/WorkPiece.cpp