MUQ: Covariance Kernels
Covariance Kernels
Detailed Description
Gaussian processes are defined by their mean function and covariance kernel. In this group, we provide tools for constructing and using covariance kernels. Several simple kernels are provided as well as tools for combining simple kernels into more complicated kernels.
C++11 introduced the "auto" keyword that tells the compiler to try to automatically detect the type of a variable. For example, consider a kernel of the form
\[ k(x,y) = k_1(x,y) * k_2(x,y) + k_3(x,y), \]
where \(k_1\) is a squared exponential kernel, \(k_2\) is a periodic kernel and \(k_3\) is a white noise kernel. In code, this can be implemented as
auto kernel1 = SquaredExpKernel(var1, length1);
auto kernel2 = PeriodicKernel(var2, length2, period);
auto kernel3 = WhiteNoiseKernel(var3);
auto kernel = kernel1*kernel2 + kernel3;
or, more succinctly, as
auto kernel = SquaredExpKernel(var1, length1) * PeriodicKernel(var2, length2, period) + WhiteNoiseKernel(var3);
In either case, the kernel variable is an instance of "SumKernel<ProductKernel<SquaredExpKernel,PeriodicKernel>, WhiteNoiseKernel>". The "auto" keyword allows us to avoid typing this long type.
Classes
class muq::Approximation::ProductKernel< LeftType, RightType >
class muq::Approximation::SumKernel< LeftType, RightType >
class muq::Approximation::KernelBase
Base class for covariance kernels.
class muq::Approximation::KernelImpl< ChildType >
class muq::Approximation::WhiteNoiseKernel
class muq::Approximation::SquaredExpKernel
class muq::Approximation::ConstantKernel
class muq::Approximation::CoregionalKernel
class muq::Approximation::ConcatenateKernel< KernelType1, KernelType2 >
class muq::Approximation::LinearTransformKernel< KernelType >
class PeriodicKernel
Functions
template<typename KernelType >
LinearTransformKernel< KernelType > muq::Approximation::TransformKernel (Eigen::MatrixXd const &A, KernelType const &K)
template<typename KernelType , typename = typename std::enable_if<std::is_base_of<KernelImpl<KernelType>, KernelType>::value, KernelType>::type>
LinearTransformKernel< KernelType > muq::Approximation::operator* (Eigen::MatrixXd const &A, KernelType const &K)
template<class KernelType1 , class... KTypes>
void muq::Approximation::FillKernelVector (std::vector< std::shared_ptr< KernelBase >> &vec, const KernelType1 &kernel1, const KTypes &... kernels)
void muq::Approximation::FillKernelVector (std::vector< std::shared_ptr< KernelBase >> &vec, KernelBase const &kernel1)
template<typename... KTypes>
CoregionalKernel muq::Approximation::CoregionTie (Eigen::MatrixXd const &coCov, const KernelBase &kernel1, const KernelBase &kernel2, const KTypes &... kernels)
CoregionalKernel muq::Approximation::CoregionTie (Eigen::MatrixXd const &coCov, KernelBase const &kernel1, int numRepeat)
template<class KernelType1 , class KernelType2 >
ConcatenateKernel< KernelType1, KernelType2 > muq::Approximation::Concatenate (KernelType1 const &kernel1, KernelType2 const &kernel2)
Function Documentation
Concatenate()
template<class KernelType1 , class KernelType2 > ConcatenateKernel<KernelType1, KernelType2> muq::Approximation::Concatenate (KernelType1 const & kernel1, KernelType2 const & kernel2)
Definition at line 1232 of file CovarianceKernels.h.
CoregionTie() [1/2]
template<typename... KTypes> CoregionalKernel muq::Approximation::CoregionTie (Eigen::MatrixXd const & coCov, const KernelBase & kernel1, const KernelBase & kernel2, const KTypes &... kernels)
Create a coregional kernel
Parameters
[in] coCov The joint covariance of the vector-valued process
[in] kernels Covariance kernels for the principal components of the covariance.
Definition at line 1214 of file CovarianceKernels.h.
References muq::Approximation::FillKernelVector(), and muq::Approximation::KernelBase::inputDim.
CoregionTie() [2/2]
CoregionalKernel muq::Approximation::CoregionTie (Eigen::MatrixXd const & coCov, KernelBase const & kernel1, int numRepeat)
Definition at line 1222 of file CovarianceKernels.h.
References muq::Approximation::KernelBase::Clone(), and muq::Approximation::KernelBase::inputDim.
FillKernelVector() [1/2]
template<class KernelType1 , class... KTypes> void muq::Approximation::FillKernelVector (std::vector< std::shared_ptr< KernelBase >> & vec, const KernelType1 & kernel1, const KTypes &... kernels)
Definition at line 1194 of file CovarianceKernels.h.
Referenced by muq::Approximation::CoregionTie().
FillKernelVector() [2/2]
void muq::Approximation::FillKernelVector (std::vector< std::shared_ptr< KernelBase >> & vec, KernelBase const & kernel1)
Definition at line 1200 of file CovarianceKernels.h.
References muq::Approximation::KernelBase::Clone().
operator*()
template<typename KernelType , typename = typename std::enable_if<std::is_base_of<KernelImpl<KernelType>, KernelType>::value, KernelType>::type> LinearTransformKernel<KernelType> muq::Approximation::operator* (Eigen::MatrixXd const & A, KernelType const & K)
Definition at line 1187 of file CovarianceKernels.h.
References muq::Approximation::TransformKernel().
TransformKernel()
template<typename KernelType > LinearTransformKernel<KernelType> muq::Approximation::TransformKernel (Eigen::MatrixXd const & A, KernelType const & K)
Definition at line 1181 of file CovarianceKernels.h.
Referenced by muq::Approximation::operator*().