MUQ: FindPtreeParameters Namespace Reference
FindPtreeParameters Namespace Reference
Functions
def PrintChild (node, graph, data, isLast)
Variables
baseFolder = sys.argv[1]
f = open(baseFolder+'/MUQdocumentation/doxFiles/listHeader.txt','r')
headerLines = f.read()
p = subprocess.Popen(["find",baseFolder+"/modules","-type","f", "-name","*.cpp", "-exec", "grep","-ni","\.get(\|ReadAndLogParameter","{}","+"],stdout=subprocess.PIPE)
out = str(out).split('\n')
err
list filenames = []
list allData = []
list fileList = []
list lineNumList = []
list varList = []
list defaultList = []
allLines = f.read()
startInd = m.start()
endInd = startInd
int openBrackets = 0
int closedBrackets = 0
int lineNum = allLines[0:startInd].count('\n')+1
tempInd = file.find('MUQ/modules')
unpacked = allLines[startInd:endInd].replace("\n","").split(',')
variable = variable.strip().strip('"')
default = default.strip()
graph = OrderedDict()
data = dict()
isRoot = dict()
allNodes = x[0].split('.')
string key = '.'.join(allNodes[0:j])
string child = '.'.join(allNodes[0:j+1])
Function Documentation
PrintChild()
def FindPtreeParameters.PrintChild (node, graph, data, isLast)
Definition at line 106 of file FindPtreeParameters.py.
Variable Documentation
allData
list FindPtreeParameters.allData = []
Definition at line 27 of file FindPtreeParameters.py.
allLines
FindPtreeParameters.allLines = f.read()
Definition at line 47 of file FindPtreeParameters.py.
allNodes
FindPtreeParameters.allNodes = x[0].split('.')
Definition at line 91 of file FindPtreeParameters.py.
baseFolder
FindPtreeParameters.baseFolder = sys.argv[1]
Definition at line 7 of file FindPtreeParameters.py.
child
string FindPtreeParameters.child = '.'.join(allNodes[0:j+1])
Definition at line 96 of file FindPtreeParameters.py.
Referenced by muq::Utilities::H5Object.Print().
closedBrackets
int FindPtreeParameters.closedBrackets = 0
Definition at line 54 of file FindPtreeParameters.py.
data
FindPtreeParameters.data = dict()
Definition at line 87 of file FindPtreeParameters.py.
Referenced by muq::Modeling::ODEBase.EvaluateRHS(), muq::Modeling::RootfindingIVP.EvaluateRoot(), muq::Modeling::RootfindingIVP.FindRoot(), muq::Modeling::ODEBase.ForwardSensitivityRHS(), muq::Utilities::HDF5File.GetVectorAttribute(), muq::Modeling::ODE.Integrate(), muq::Modeling::ODEBase.RHSJacobian(), and muq::Modeling::ODEBase.RHSJacobianAction().
default
FindPtreeParameters.default = default.strip()
Definition at line 73 of file FindPtreeParameters.py.
defaultList
list FindPtreeParameters.defaultList = []
Definition at line 40 of file FindPtreeParameters.py.
endInd
FindPtreeParameters.endInd = startInd
Definition at line 52 of file FindPtreeParameters.py.
err
FindPtreeParameters.err
Definition at line 24 of file FindPtreeParameters.py.
f
FindPtreeParameters.f = open(baseFolder+'/MUQdocumentation/doxFiles/listHeader.txt','r')
Definition at line 15 of file FindPtreeParameters.py.
Referenced by muq::Utilities::HDF5File.DoesFileExist(), muq::Modeling::RootfindingIVP.JacobianImpl(), and main().
fileList
list FindPtreeParameters.fileList = []
Definition at line 37 of file FindPtreeParameters.py.
filenames
FindPtreeParameters.filenames = []
Definition at line 26 of file FindPtreeParameters.py.
Referenced by main().
graph
FindPtreeParameters.graph = OrderedDict()
Definition at line 86 of file FindPtreeParameters.py.
Referenced by muq::Modeling::WorkGraph.AddEdge(), muq::Modeling::WorkGraph.AddNode(), muq::Modeling::WorkGraph.Constant(), muq::Modeling::WorkGraph.CreateWorkPiece(), muq::Modeling::WorkGraph.DependentCut(), muq::Modeling::WorkGraph.GetConstantOutputs(), muq::Modeling::WorkGraph.GetNodeIterator(), muq::Modeling::WorkGraph.GraphInputs(), muq::Modeling::WorkGraph.GraphOutputs(), muq::Modeling::WorkGraph.HasEdge(), muq::Modeling::WorkGraph.HasNode(), muq::Modeling::WorkGraph.NumEdges(), muq::Modeling::WorkGraph.NumNodes(), muq::Modeling::WorkGraph.Visualize(), and muq::Modeling::WorkGraph.WorkGraph().
headerLines
FindPtreeParameters.headerLines = f.read()
Definition at line 16 of file FindPtreeParameters.py.
isRoot
FindPtreeParameters.isRoot = dict()
Definition at line 88 of file FindPtreeParameters.py.
key
string FindPtreeParameters.key = '.'.join(allNodes[0:j])
Definition at line 95 of file FindPtreeParameters.py.
lineNum
int FindPtreeParameters.lineNum = allLines[0:startInd].count('\n')+1
Definition at line 62 of file FindPtreeParameters.py.
lineNumList
list FindPtreeParameters.lineNumList = []
Definition at line 38 of file FindPtreeParameters.py.
openBrackets
int FindPtreeParameters.openBrackets = 0
Definition at line 53 of file FindPtreeParameters.py.
out
FindPtreeParameters.out = str(out).split('\n')
Definition at line 24 of file FindPtreeParameters.py.
Referenced by muq::Modeling::WorkGraph.CreateWorkPiece(), muq::Modeling::WorkGraphPiece.JacobianActionImpl(), muq::Modeling::WorkGraphPiece.JacobianImpl(), muq::Modeling::WorkGraphPiece.JacobianTransposeActionImpl(), and muq::Modeling::WorkGraph.Visualize().
p
FindPtreeParameters.p = subprocess.Popen(["find",baseFolder+"/modules","-type","f", "-name","*.cpp", "-exec", "grep","-ni","\.get(\|ReadAndLogParameter","{}","+"],stdout=subprocess.PIPE)
Definition at line 22 of file FindPtreeParameters.py.
startInd
FindPtreeParameters.startInd = m.start()
Definition at line 51 of file FindPtreeParameters.py.
Referenced by muq::Utilities::H5Object.eval().
tempInd
FindPtreeParameters.tempInd = file.find('MUQ/modules')
Definition at line 64 of file FindPtreeParameters.py.
unpacked
FindPtreeParameters.unpacked = allLines[startInd:endInd].replace("\n","").split(',')
Definition at line 69 of file FindPtreeParameters.py.
variable
FindPtreeParameters.variable = variable.strip().strip('"')
Definition at line 72 of file FindPtreeParameters.py.
varList
list FindPtreeParameters.varList = []
Definition at line 39 of file FindPtreeParameters.py.