MUQ: muq::Utilities Namespace Reference
muq::Utilities Namespace Reference
Classes
class Attribute
class AttributeList
class BlockDataset
class H5Object
struct HDF5_Type
struct HDF5_Type< bool >
struct HDF5_Type< char >
struct HDF5_Type< double >
struct HDF5_Type< float >
struct HDF5_Type< int >
struct HDF5_Type< long >
struct HDF5_Type< long double >
struct HDF5_Type< short >
struct HDF5_Type< unsigned >
struct HDF5_Type< unsigned long >
struct HDF5_Type< unsigned short >
class HDF5File
A wrapper around HDF5 (and PHDF5) to handle file I/O.
Functions
H5Object AddChildren (std::shared_ptr< HDF5File > file, std::string const &groupName)
Recursively add children to create an HDF5 file hierarchy.
H5Object OpenFile (std::string const &filename)
Open an HDF5 file and return the root object.
herr_t H5LTset_attribute (hid_t loc_id, const char *obj_name, const char *attr_name, hid_t mem_type_id, void *buffer, size_t size)
std::string GetParentPath (std::string const &base)
Get the parent folder of a path.
std::pair< std::string, std::string > SplitString (std::string const &path)
Splits a string on the first forward slash.
Function Documentation
AddChildren()
H5Object muq::Utilities::AddChildren (std::shared_ptr< HDF5File > file, std::string const & groupName)
Recursively add children to create an HDF5 file hierarchy.
Definition at line 252 of file H5Object.cpp.
References muq::Utilities::H5Object::children, and muq::Utilities::H5Object::H5Object().
Referenced by OpenFile().
GetParentPath()
std::string muq::Utilities::GetParentPath (std::string const & base)
Get the parent folder of a path.
Given a path of the form /a/b/c, return the parent path /a/b
std::string base   = "/some/path";
std::string parent = GetParent(base);
Parent now holds "/some"
Definition at line 6 of file PathTools.cpp.
Referenced by muq::Utilities::HDF5File::CreateGroup(), muq::Utilities::HDF5File::DoesDataSetExist(), muq::Utilities::HDF5File::DoesGroupExist(), and muq::Utilities::HDF5File::WriteMatrix().
H5LTset_attribute()
herr_t muq::Utilities::H5LTset_attribute (hid_t loc_id, const char * obj_name, const char * attr_name, hid_t mem_type_id, void * buffer, size_t size)
Definition at line 19 of file HDF5Types.cpp.
Referenced by muq::Utilities::HDF5File::WriteVectorAttribute().
OpenFile()
H5Object muq::Utilities::OpenFile (std::string const & filename)
Open an HDF5 file and return the root object.
Primary way to open an HDF5file. It returns the root group.
// Open the HDF5 file for reading and writing
auto f = muq::Utilities::OpenFile("Data.h5");
// Create a new group
f.CreateGroup("/NewGroup");
// Add an attribute to the group
f["/NewGroup"].attrs["Some Metadata"] = "Created with MH5!";
// Store a vector in the group
f["/NewGroup/Ones"] = Eigen::VectorXd::Ones(10);
// Store another vector in a different group.  The group is automatically generated
f["/AnotherGroup/Zeros"] = Eigen::MatrixXd::Zero(5,5);
Definition at line 281 of file H5Object.cpp.
References AddChildren(), and muq::Utilities::H5Object::file.
Referenced by main().
SplitString()
std::pair< std::string, std::string > muq::Utilities::SplitString (std::string const & path)
Splits a string on the first forward slash.
Given a path, like "/a/b/c", this function returns two strings, "/a", and "/b/c". [in] path The original plan to split.
Returns
A pair of std::string holind the two components of the path.
Definition at line 19 of file PathTools.cpp.
Referenced by muq::Utilities::H5Object::CreateDataset(), muq::Utilities::H5Object::CreateGroup(), and muq::Utilities::H5Object::operator[]().