MUQ: /Users/andy/software/muq-private/external/include/stan/command/print.cpp File Reference
print.cpp File Reference
#include <algorithm>
#include <iostream>
#include <iomanip>
#include <ios>
#include <stan/mcmc/chains.hpp>
Functions
int calculate_size (const Eigen::VectorXd &x, const std::string &name, const int digits, std::ios_base::fmtflags &format)
Eigen::VectorXi calculate_sizes (const Eigen::MatrixXd &values, const Eigen::Matrix< std::string, Eigen::Dynamic, 1 > &headers, const Eigen::VectorXi &digits, Eigen::Matrix< std::ios_base::fmtflags, Eigen::Dynamic, 1 > &formats)
void print_usage ()
int main (int argc, const char *argv[])
Function Documentation
calculate_size()
int calculate_size (const Eigen::VectorXd & x, const std::string & name, const int digits, std::ios_base::fmtflags & format)
Definition at line 9 of file print.cpp.
Referenced by calculate_sizes().
calculate_sizes()
Eigen::VectorXi calculate_sizes (const Eigen::MatrixXd & values, const Eigen::Matrix< std::string, Eigen::Dynamic, 1 > & headers, const Eigen::VectorXi & digits, Eigen::Matrix< std::ios_base::fmtflags, Eigen::Dynamic, 1 > & formats)
Definition at line 47 of file print.cpp.
References calculate_size().
main()
int main (int argc, const char * argv[])
The Stan print function.
Parameters
argc Number of arguments
argv Arguments
Returns
0 for success, non-zero otherwise
Definition at line 76 of file print.cpp.
References FindPtreeParameters::filenames, and print_usage().
print_usage()
void print_usage ()
Definition at line 62 of file print.cpp.
Referenced by main().