MUQ: muq::Utilities::HDF5_Type< scalarType > Struct Template Reference
muq::Utilities::HDF5_Type< scalarType > Struct Template Reference
#include <HDF5Types.h>
Detailed Description
template<typename scalarType>
struct muq::Utilities::HDF5_Type< scalarType >
Definition at line 69 of file HDF5Types.h.
Static Public Member Functions
static hid_t GetFlag ()
Member Function Documentation
GetFlag()
template<typename scalarType > hid_t HDF5_Type::GetFlag () inline static
Definition at line 70 of file HDF5Types.h.
Referenced by muq::Utilities::HDF5File::GetVectorAttribute(), muq::Utilities::HDF5File::WriteMatrix(), and muq::Utilities::HDF5File::WriteVectorAttribute().
The documentation for this struct was generated from the following files:
/Users/andy/software/muq-private/MUQ/Utilities/HDF5/HDF5Types.h
/Users/andy/software/muq-private/modules/Utilities/src/HDF5/HDF5Types.cpp