set(MUQ_SHARED_LIB_SUFFIX ${CMAKE_SHARED_LIBRARY_SUFFIX})

if(APPLE AND MUQ_USE_PYTHON)
	 set(MUQ_SHARED_LIB_SUFFIX ".so")
endif(APPLE AND MUQ_USE_PYTHON)


foreach(libName ${MUQ_TARGETS})

    list(LENGTH ${libName}_SOURCES strLength)
    if(${strLength} GREATER 0)

        list(APPEND MUQ_BUILT_LIBRARIES ${CMAKE_SHARED_LIBRARY_PREFIX}${libName}${MUQ_SHARED_LIB_SUFFIX})

    endif()
    
endforeach()

message("MUQ_BUILT_LIBRARIES = ${MUQ_BUILT_LIBRARIES}")