set(MUQ_SHARED_LIB_SUFFIX ${CMAKE_SHARED_LIBRARY_SUFFIX})

if(UtilitiesAndModelling_build)
	#list(APPEND MUQ_BUILT_LIBRARIES ${CMAKE_SHARED_LIBRARY_PREFIX}muqUtilities${MUQ_SHARED_LIB_SUFFIX})
	#list(APPEND MUQ_BUILT_LIBRARIES ${CMAKE_SHARED_LIBRARY_PREFIX}muqModelling${MUQ_SHARED_LIB_SUFFIX})
endif()
