set(MUQ_SHARED_LIB_SUFFIX ${CMAKE_SHARED_LIBRARY_SUFFIX})

if(APPLE AND MUQ_USE_PYTHON)
	 set(MUQ_SHARED_LIB_SUFFIX ".so")
endif(APPLE AND MUQ_USE_PYTHON)


if(Approximation_build)
	list(APPEND MUQ_BUILT_LIBRARIES ${CMAKE_SHARED_LIBRARY_PREFIX}muqApproximation${MUQ_SHARED_LIB_SUFFIX})
endif()

if(Inference_build)
	list(APPEND MUQ_BUILT_LIBRARIES ${CMAKE_SHARED_LIBRARY_PREFIX}muqInference${MUQ_SHARED_LIB_SUFFIX})
endif()

if(Optimization_build)
	list(APPEND MUQ_BUILT_LIBRARIES ${CMAKE_SHARED_LIBRARY_PREFIX}muqOptimization${MUQ_SHARED_LIB_SUFFIX})
endif()

if(Geostats_build)
	list(APPEND MUQ_BUILT_LIBRARIES ${CMAKE_SHARED_LIBRARY_PREFIX}muqGeostatistics${MUQ_SHARED_LIB_SUFFIX})
endif()

if(UtilitiesAndModelling_build)
	list(APPEND MUQ_BUILT_LIBRARIES ${CMAKE_SHARED_LIBRARY_PREFIX}muqUtilities${MUQ_SHARED_LIB_SUFFIX})
	list(APPEND MUQ_BUILT_LIBRARIES ${CMAKE_SHARED_LIBRARY_PREFIX}muqModelling${MUQ_SHARED_LIB_SUFFIX})
endif()

if(PDE_build)
	list(APPEND MUQ_BUILT_LIBRARIES ${CMAKE_SHARED_LIBRARY_PREFIX}muqPde${MUQ_SHARED_LIB_SUFFIX})
endif()